#-
#              _                        _   _
#   __ _ _   _| |_ ___  _ __ ___   __ _| |_(_) ___  _ __  ___
#  / _` | | | | __/ _ \| '_ ` _ \ / _` | __| |/ _ \| '_ \/ __|
# | (_| | |_| | || (_) | | | | | | (_| | |_| | (_) | | | \__ \
#  \__,_|\__,_|\__\___/|_| |_| |_|\__,_|\__|_|\___/|_| |_|___/
#
#
#- from github.com/tmttn/home-assistant-config
- id: '1636727868357'
  alias: 'Vacuum: disable vacuum camera update when docked'
  description: ''
  use_blueprint:
    path: PiotrMachowski/disable_vacuum_camera_update_when_docked.yaml
    input:
      vacuum: vacuum.robot_vacuum
      camera: camera.xiaomi_cloud_map_extractor
- id: '1667822050564'
  alias: 'Adaptive lighting: notify manual_control'
  description: ''
  trigger:
  - platform: event
    event_type: adaptive_lighting.manual_control
  condition: []
  action:
  - service: system_log.write
    data:
      message: '{{ light }} is manually controlled'
      level: error
      logger: yolo.yolo
  - service: notify.mobile_app_bizzyphone
    data:
      title: 'Adaptive Ligthing: manual_control'
      message: '{{ light }} is now ''manually controlled'', context={{ trigger.event.context
        }}'
  mode: parallel
  max: 20
  variables:
    light: '{{ trigger.event.data.entity_id }}'
- id: '1667822131571'
  alias: 'Adaptive lighting: reset manual_control after 1 hour'
  description: ''
  trigger:
  - platform: event
    event_type: adaptive_lighting.manual_control
  condition:
  - '{{ ''hall'' not in light and ''stairs'' not in light }}'
  action:
  - delay: 01:00:00
  - condition: template
    value_template: '{{ light in state_attr(''switch'', ''manual_control'') }}'
  - service: adaptive_lighting.set_manual_control
    data:
      entity_id: '{{ switch }}'
      lights: '{{ light }}'
      manual_control: false
  - service: notify.mobile_app_bizzyphone
    data:
      title: 'Adaptive Ligthing: manual_control reset'
      message: '{{ light }} is reset to not ''manually controlled'''
  mode: parallel
  max: 200
  variables:
    light: '{{ trigger.event.data.entity_id }}'
    switch: '{{ trigger.event.data.switch }}'
- id: '1667822350382'
  alias: 'Adaptive lighting: turn on and off switches'
  description: ''
  trigger:
  - platform: state
    entity_id: input_select.sleep_mode
  - platform: homeassistant
    event: start
  condition: []
  action:
  - choose:
    - conditions: '{{ sleep_mode == ''off'' }}'
      sequence:
      - service: switch.turn_off
        entity_id:
        - switch.adaptive_lighting_half_and_dim
        - switch.adaptive_lighting_half_and_full
        - switch.adaptive_lighting_sleep_mode_default
        - switch.adaptive_lighting_sleep_mode_living_room
      - service: switch.turn_on
        entity_id:
        - switch.adaptive_lighting_default
    - conditions: '{{ sleep_mode == ''half'' }}'
      sequence:
      - service: switch.turn_off
        entity_id:
        - switch.adaptive_lighting_default
        - switch.adaptive_lighting_sleep_mode_half_and_full
      - service: switch.turn_on
        entity_id:
        - switch.adaptive_lighting_half_and_dim
        - switch.adaptive_lighting_half_and_full
        - switch.adaptive_lighting_sleep_mode_half_and_dim
    - conditions: '{{ sleep_mode == ''total'' }}'
      sequence:
      - service: switch.turn_off
        entity_id:
        - switch.adaptive_lighting_half_and_dim
        - switch.adaptive_lighting_half_and_full
      - service: switch.turn_on
        entity_id:
        - switch.adaptive_lighting_default
        - switch.adaptive_lighting_sleep_mode_default
  mode: single
  variables:
    sleep_mode: '{{ states(''input_select.sleep_mode'') }}'
- id: '1667822399597'
  alias: 'Alarm clock: wake up'
  description: ''
  trigger:
  - platform: template
    value_template: '{{ states("sensor.time")[0:5] == states("sensor.ten_minutes_before_alarm")
      }}

      '
  condition:
  - condition: state
    entity_id: input_boolean.alarm_clock
    state: 'on'
  action:
  - service: input_boolean.turn_off
    entity_id: input_boolean.alarm_clock
  - service: input_boolean.turn_on
    entity_id: input_boolean.wake_up_light
  - service: input_select.select_option
    entity_id: input_select.sleep_mode
    data:
      option: 'off'
  mode: single
