#!/bin/bash

#    ____ _
#   / ___| |__   ___  _ __ ___  ___
#  | |   | '_ \ / _ \| '__/ _ \/ __|
#  | |___| | | | (_) | | |  __/\__ \
#   \____|_| |_|\___/|_|  \___||___/
#
#- from github.com/tmttn/home-assistant-config

python3 utils/commit-updates.py
python3 -m pip install --upgrade pip
pip3 -q install pyfiglet > /dev/null
python3 utils/ascii_art.py
python3 utils/update-readme.py
./utils/commit-readme.sh
