---
- platform: template
  switches:
    copy:
      value_template: "{{ is_state('sensor.desk_lamp_current', 'on') }}"
      turn_on:
        service: switch.turn_on
        entity_id: switch.light2
      turn_off:
        service: switch.turn_off
        entity_id: switch.light2

    kef_speakers:
      friendly_name: KEF Speakers
      value_template: "{{ is_state('media_player.kef', 'on') }}"
      availability_template: >-
        {{ not is_state('media_player.kef', 'unavailable') }}
      turn_on:
        - service: media_player.turn_on
          entity_id: media_player.kef
      turn_off:
        - service: media_player.turn_off
          entity_id: media_player.kef
