---
# Kitchen
- alias: "Activity: activity in kitchen"
  trigger:
    platform: state
    entity_id: binary_sensor.presence_1
    to: "on"
  action:
    service: input_boolean.turn_on
    entity_id: input_boolean.activity_in_kitchen

- alias: "Activity: no activity in kitchen"
  trigger:
    platform: state
    entity_id: binary_sensor.presence_1
    to: "off"
    for: "00:05:00"
  action:
    service: input_boolean.turn_off
    entity_id: light.activity_in_kitchen

# Hall
- alias: "Activity: activity in hall"
  trigger:
    platform: state
    entity_id: binary_sensor.presence_2
    to: "on"
  action:
    service: input_boolean.turn_on
    entity_id: input_boolean.activity_in_hall

- alias: "Activity: no activity in the hall"
  trigger:
    platform: state
    entity_id: binary_sensor.presence_2
    to: "off"
    for: "00:05:00"
  action:
    service: input_boolean.turn_off
    entity_id: light.activity_in_hall

# Toilet
- alias: "Activity: activity at the toilet"
  trigger:
    platform: state
    entity_id: binary_sensor.presence_3
    to: "on"
  action:
    service: input_boolean.turn_on
    entity_id: input_boolean.activity_in_toilet

- alias: "Activity: no activity at the toilet"
  trigger:
    platform: state
    entity_id: binary_sensor.presence_3
    to: "off"
    for: "00:05:00"
  action:
    service: input_boolean.turn_off
    entity_id: light.activity_in_toilet
