---
#-
#                    _                      _       _
#   __ _ _ __  _ __ | | ___  __      ____ _| |_ ___| |__
#  / _` | '_ \| '_ \| |/ _ \ \ \ /\ / / _` | __/ __| '_ \
# | (_| | |_) | |_) | |  __/  \ V  V / (_| | || (__| | | |
#  \__,_| .__/| .__/|_|\___|___\_/\_/ \__,_|\__\___|_| |_|
#       |_|   |_|         |_____|
#
#- from github.com/basnijholt/home-assistant-config
- alias: "Apple Watch: Play or Pause the TV"
  trigger:
    platform: event
    event_type: ios.action_fired
    event_data:
      actionName: Play TV
  condition:
    condition: state
    entity_id: media_player.tv
    state: "on"
  action:
    service: media_player.media_play_pause
    entity_id: media_player.tv

- alias: "Apple Watch: One person goes to sleep"
  trigger:
    platform: event
    event_type: ios.action_fired
    event_data:
      actionName: Half sleep mode
  action:
    service: input_select.select_option
    data:
      entity_id: input_select.sleep_mode
      option: "half"

- alias: "Apple Watch: set sleep mode"
  mode: parallel
  trigger:
    platform: event
    event_type: ios.action_fired
    event_data:
      actionName: Set sleep mode
  action:
    - service: notify.mobile_app_basnijholt_iphone
      data:
        message: "Apple Watch: set sleep mode."
        data:
          push:
            category: set_sleep_mode
    - wait_for_trigger:
        platform: event
        event_type: ios.notification_action_fired
        event_data:
          categoryName: set_sleep_mode
    - variables:
        event: "{{ wait.trigger.event.data.actionName.split('SET_SLEEP_MODE_')[1].lower() }}"
    - service: input_select.select_option
      data:
        entity_id: input_select.sleep_mode
        option: "{{ event }}"

- alias: "Apple Watch: set lights"
  mode: parallel
  trigger:
    platform: event
    event_type: ios.action_fired
    event_data:
      actionName: Set lights
  action:
    - service: notify.mobile_app_basnijholt_iphone
      data:
        message: "Apple Watch: set lights"
        data:
          push:
            category: set_lights
    - wait_for_trigger:
        platform: event
        event_type: ios.notification_action_fired
        event_data:
          categoryName: set_lights
      timeout: "00:00:20"
      continue_on_timeout: false
    - variables:
        light: >
          {{
            {'LIGHTS_ALL': 'all',
             'LIGHTS_BEDROOM': 'light.bedroom_lights',
             'LIGHTS_LIVING_ROOM': 'light.living_room_lights',
             'LIGHTS_BATHROOM': 'light.ceiling_bathroom',
             'LIGHTS_HALL_AND_STAIRS': 'light.hall_lights,light.stairs_lights',
             'LIGHTS_TOILET': 'light.toilet',
             'LIGHTS_KITCHEN': 'light.kitchen_lights',
            }[wait.trigger.event.data.actionName] }}
    - service: notify.mobile_app_basnijholt_iphone
      data:
        message: "Apple Watch: choose option"
        data:
          push:
            category: light_options
    - wait_for_trigger:
        platform: event
        event_type: ios.notification_action_fired
        event_data:
          categoryName: light_options
      timeout: "00:00:20"
      continue_on_timeout: false
    - variables:
        option: "{{ wait.trigger.event.data.actionName }}"
    - choose:
        - conditions: "{{ option == 'OFF' }}"
          sequence:
            service: light.turn_off
            data:
              entity_id: "{{ light }}"
        - conditions: "{{ option == 'ON' }}"
          sequence:
            service: light.turn_on
            data:
              entity_id: "{{ light }}"
        - conditions: "{{ option == 'FIFTY' }}"
          sequence:
            service: light.turn_on
            data:
              entity_id: "{{ light }}"
              brightness_pct: 50
        - conditions: "{{ option == 'HUNDRED' }}"
          sequence:
            service: light.turn_on
            data:
              entity_id: "{{ light }}"
              brightness_pct: 100
        - conditions: "{{ option == 'ONE' }}"
          sequence:
            service: light.turn_on
            data:
              entity_id: "{{ light }}"
              brightness_pct: 1
        - conditions: "{{ option == 'WHITE' and light == 'light.living_room_lights'}}"
          sequence:
            service: script.white_lights_living_room
        - conditions: "{{ option == 'WHITE' and light == 'light.bedroom_lights'}}"
          sequence:
            service: script.white_lights_living_room
        - conditions: "{{ option == 'COZY' and light == 'light.living_room_lights'}}"
          sequence:
            service: script.cozy_lights_living_room
        - conditions: "{{ option == 'COZY' and light == 'light.bedroom_lights'}}"
          sequence:
            service: script.cozy_lights_bedroom

- alias: "Apple Watch: temperature report"
  mode: parallel
  trigger:
    platform: event
    event_type: ios.action_fired
    event_data:
      actionName: Temperature report
  action:
    - service: notify.mobile_app_basnijholt_iphone
      data:
        title: "Temperature"
        message: >
          Bedroom: {{ states('sensor.temperature_bedroom') }}°C
          Living room: {{ states('sensor.temperature_living_room') }}°C
          Hall: {{ states('sensor.temperature_hall') }}°C
          Thermostat: {{ state_attr('climate.thermostat', 'temperature') }}°C
          Outside: {{ state_attr('weather.huis', 'temperature') }}°C and it's {{ states('weather.huis') }}
