---
#-
#                    _                      _       _
#   __ _ _ __  _ __ | | ___  __      ____ _| |_ ___| |__
#  / _` | '_ \| '_ \| |/ _ \ \ \ /\ / / _` | __/ __| '_ \
# | (_| | |_) | |_) | |  __/  \ V  V / (_| | || (__| | | |
#  \__,_| .__/| .__/|_|\___|___\_/\_/ \__,_|\__\___|_| |_|
#       |_|   |_|         |_____|
#
#- from github.com/basnijholt/home-assistant-config
- alias: "Apple Watch: Play or Pause the TV"
  trigger:
    platform: event
    event_type: ios.action_fired
    event_data:
      actionName: Play TV
  condition:
    condition: state
    entity_id: media_player.tv
    state: "on"
  action:
    service: media_player.media_play_pause
    entity_id: media_player.tv

- alias: "Apple Watch: One person goes to sleep"
  trigger:
    platform: event
    event_type: ios.action_fired
    event_data:
      actionName: Half sleep mode
  action:
    service: input_select.select_option
    data:
      entity_id: input_select.sleep_mode
      option: "half"

- alias: "Apple Watch: set sleep mode"
  mode: parallel
  trigger:
    platform: event
    event_type: ios.action_fired
    event_data:
      actionName: Set sleep mode
  action:
    - service: notify.mobile_app_basnijholt_iphone
      data:
        message: "Apple Watch: set sleep mode."
        data:
          push:
            category: set_sleep_mode
    - wait_for_trigger:
        platform: event
        event_type: ios.notification_action_fired
    - variables:
        event: "{{ wait.trigger.event.data.actionName.split('SET_SLEEP_MODE_')[1].lower() }}"
    - service: input_select.select_option
      data:
        entity_id: input_select.sleep_mode
        option: "{{ event }}"
