---
#-
#                      _
#   ___ __ _ _ __   __| |_   _
#  / __/ _` | '_ \ / _` | | | |
# | (_| (_| | | | | (_| | |_| |
#  \___\__,_|_| |_|\__,_|\__, |
#                        |___/
#
#- from github.com/tmttn/home-assistant-config
- alias: "Candy: Marthe candy button pressed"
  id: "candy_marthe-candy-button-pressed"
  mode: single
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: smart_switch_kitchen_candy
  condition: "{{ trigger.event.data.event == 1002 }}" #Single click
  action:
    - service: media_player.volume_set
      entity_id: media_player.kitchen_display
      data:
        volume_level: 0.6
    - choose:
        - conditions:
            - condition: time
              weekday:
                - tue
                - thu
                - sat
          sequence:
            - service: tts.google_translate_say
              data:
                entity_id: media_player.kitchen_display
                language: nl
                message: Het is vandaag geen snoepdag. Je mag vandaag geen snoepjes.
        - conditions:
            - condition: state
              entity_id: input_boolean.marthe_candy
              state: "on"
          sequence:
            - service: tts.google_translate_say
              data:
                entity_id: media_player.kitchen_display
                language: nl
                message: Stop! Jij hebt al een snoepje gekregen. Geen snoepjes meer vandaag, anders krijg je rotte tandjes.
        - conditions:
            - condition: state
              entity_id: input_boolean.marthe_candy
              state: "off"
            - condition: time
              before: "10:00:00"
          sequence:
            - service: tts.google_translate_say
              data:
                entity_id: media_player.kitchen_display
                language: nl
                message: Nu al een snoepje, nee dat is veel te vroeg hoor. Moet jij niet eerst ontbijten?
        - conditions:
            - condition: state
              entity_id: input_boolean.marthe_candy
              state: "off"
          sequence:
            - service: tts.google_translate_say
              data:
                entity_id: media_player.kitchen_display
                language: nl
                message: Ja hoor, neem maar een snoepje Marthe. Lekker!
            - service: input_boolean.turn_on
              data: {}
              target:
                entity_id: input_boolean.marthe_candy

- alias: "Candy: reset input_boolean Marthe candy at midnight"
  id: "candy_marthe-candy-reset-at-midnight"
  trigger:
    platform: time
    at: "00:00"
  condition:
    condition: state
    entity_id: input_boolean.marthe_candy
    state: "on"
  action:
    service: input_boolean.turn_off
    entity_id: input_boolean.marthe_candy
