---
- alias: "Candy: Marthe candy button pressed"
  id: "candy_marthe-candy-button-pressed"
  mode: single
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: smart_switch_kitchen_candy
  condition: "{{ trigger.event.data.event == 1002 }}" #Single click
  action:
    - service: media_player.volume_set
      entity_id: media_player.kitchen_display
      data:
        volume_level: 0.6
    - choose:
        - conditions:
            - condition: state
              entity_id: input_boolean.marthe_candy
              state: "off"
          sequence:
            - service: tts.google_translate_say
              data:
                entity_id: media_player.kitchen_display
                language: nl
                message: Ja hoor, neem maar een snoepje Marthe. Lekker!
            - service: input_boolean.turn_on
              data: {}
              target:
                entity_id: input_boolean.marthe_candy
      default:
        - service: tts.google_translate_say
          data:
            entity_id: media_player.kitchen_display
            language: nl
            message: Stop! Jij hebt al een snoepje gekregen. Geen snoepjes meer vandaag, anders krijg je rotte tandjes.

- alias: "Candy: reset input_boolean Marthe candy at midnight"
  id: "candy_marthe-candy-reset-at-midnight"
  trigger:
    platform: time
    at: "00:00"
  condition:
    condition: state
    entity_id: input_boolean.marthe_candy
    state: "on"
  action:
    service: input_boolean.turn_off
    entity_id: input_boolean.marthe_candy
