---
#-
#                  _             _                  _ _       _
#   ___ ___  _ __ | |_ _ __ ___ | |    _____      _(_) |_ ___| |__   ___  ___
#  / __/ _ \| '_ \| __| '__/ _ \| |   / __\ \ /\ / / | __/ __| '_ \ / _ \/ __|
# | (_| (_) | | | | |_| | | (_) | |   \__ \\ V  V /| | || (__| | | |  __/\__ \
#  \___\___/|_| |_|\__|_|  \___/|_|___|___/ \_/\_/ |_|\__\___|_| |_|\___||___/
#                                |_____|
#
#- from github.com/tmttn/home-assistant-config

- alias: "Control switches: living room Philips Hue dimmer switch"
  mode: parallel
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: dimmer_switch_living_room
  action:
    choose:
      # Next color
      - conditions: "{{ trigger.event.data.event == 4002 }}" # Lowest button short release
        sequence:
          service: script.next_colors
          data:
            input_select: input_select.last_script_living_room

      # Bright lights
      - conditions:
          - "{{ trigger.event.data.event == 1002 }}" # Top button short release
        sequence:
          - service: script.white_lights_living_room
          - service: light.turn_on
            entity_id: light.living_room_lights
            data:
              brightness: "255"
      # Turn off all lights
      - conditions:
          - "{{ trigger.event.data.event == 1001 }}" # Top button repeat
        sequence:
          - service: light.turn_off
            data:
              entity_id: light.living_room_lights

      # Increase brightness
      - conditions: "{{ trigger.event.data.event == 2002 }}" # Second button short release
        sequence:
          service: script.increase_brightness
          data:
            group: light.living_room_lights

       # Decrease brightness
      - conditions: "{{ trigger.event.data.event == 3002 }}" # Third button short release
        sequence:
          service: script.decrease_brightness
          data:
            group: light.living_room_lights

- alias: "Control switches: back door Aqara Wireless Mini Switch"
  mode: parallel
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: smart_switch_back_door
  action:
    choose:
      # Leaving: turn off everything
      - conditions: "{{ trigger.event.data.event == 1002 }}" # Single click
        sequence:
          - service: script.turn_off_everything_non_automatic
          - service: script.set_low_temperature

      # Arriving: turn on cozy lights
      - conditions: "{{ trigger.event.data.event == 1004 }}" # Double click
        sequence:
          - service: script.arriving

      # Leaving: turn on music and cozy lights
      - conditions: "{{ trigger.event.data.event == 1001 }}" # Long click
        sequence:
          - service: script.arriving
          - service: script.start_spotify_playlist_of_nearest_person
            data:
              source: Google Home
              entity_id: media_player.google_home

- alias: "Control switches: bedroom wall switch"
  mode: parallel
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: bedroom_wall_switch
  action:
    choose:
      - conditions: {{ states(light.bedroom_lights) == "off" }}
        sequence:
          - service: light.turn_on
            data:
              entity_id: light.bedroom_lights)}}
              transition: 1
      - conditions: {{ states(light.bedroom_lights) == "on" }}
        sequence:
          - service: light.turn_off
            data:
              entity_id: light.bedroom_lights
              transition: 1

- alias: "Control switches: bathroom wall switch"
  mode: parallel
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: bathroom_wall_switch
  action:
    choose:
      - conditions: {{ states(light.bathroom_lights) == "off" }}
        sequence:
          - service: light.turn_on
            data:
              entity_id: light.bathroom_lights)}}
              transition: 1
      - conditions: {{ states(light.bathroom_lights) == "on" }}
        sequence:
          - service: light.turn_off
            data:
              entity_id: light.bathroom_lights
              transition: 1
