---
- alias: "Cube: change cube mode"
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: lumi_sensor_cube_aqgl01_11
  condition:
    condition: template
    value_template: >
      {{ trigger.event.data.event in (1000, 2000, 3000) }}
  action:
    - service: input_select.select_option
      entity_id: input_select.cube_mode
      data_template:
        option: >
          {{ {1000: "Volume", 2000: "Hue", 3000: "Brightness"}[trigger.event.data.event] }}
    - service: notify.tv
      data:
        message: >
          Cube mode set to {{ states("input_select.cube_mode") }}

- alias: "Cube: change hue of living room lights with cube"
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: mi_magic_cube
  condition:
    condition: state
    entity_id: input_select.cube_mode
    state: "Hue"
  action:
    service: light.turn_on
    entity_id: light.living_room_lights
    data_template:
      hs_color:
        - >
           {% set hue, sat = state_attr('light.sphere_1', 'hs_color') %}
           {% set delta = trigger.event.data.event / 450 %}
           {% set new_hue = [([0, (hue + delta)]|max), 360]|min %}
           {{ new_hue|round(3) }}
        - >
           {{ state_attr('light.sphere_1', 'hs_color')[1] }}

- alias: "Cube: change brightness of living room lights with cube"
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: mi_magic_cube
  condition:
    condition: state
    entity_id: input_select.cube_mode
    state: "Brightness"
  action:
    service: light.turn_on
    entity_id: light.living_room_lights
    data_template:
      brightness: >
        {% set brightness = state_attr('light.sphere_1', 'brightness') %}
        {% set delta = trigger.event.data.event / 450 %}
        {% set new_brightness = [([0, (brightness + delta)]|max), 255]|min %}
        {{ new_brightness|int }}

- alias: "Cube: change speaker volume by rotating cube"
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: mi_magic_cube
  condition:
    condition: state
    entity_id: input_select.cube_mode
    state: "Volume"
  action:
    - service: media_player.volume_set
      entity_id:  media_player.kef
      data_template:  # 90 deg is 10%
        volume_level: >
          {% set max_change = 0.15 %}
          {% set dV = [trigger.event.data.event / 100 / 900, max_change] | min %}
          {{ (states.media_player.kef.attributes.volume_level + dV)|round(2) }}
    - service: notify.tv
      data:
        message: >
          Volume set to {{ state_attr("media_player.kef", "volume_level") }}

- alias: "Cube: shuffle Spotify song by shaking cube"
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: lumi_sensor_cube_aqgl01_11
  condition:
    condition: and
    conditions:
      - condition: template
        value_template: >
          {{ trigger.event.data.event == 7007 }}
      - condition: template
        value_template: >
          {{ is_state_attr("media_player.spotify", "source", "LS50 Wireless 00C437")}}
  action:
    - service: media_player.shuffle_set
      entity_id: media_player.spotify
      data:
        shuffle: true
    - service: media_player.media_next_track
      entity_id: media_player.spotify

- alias: "Cube: pause and play Spotify song by tapping cube on side 1"
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: lumi_sensor_cube_aqgl01_11
  condition:
    condition: and
    conditions:
      - condition: template
        value_template: >
          {{ trigger.event.data.event == 1001 }}
      - condition: template
        value_template: >
          {{ is_state_attr("media_player.spotify", "source", "LS50 Wireless 00C437")}}
  action:
    service: media_player.media_play_pause
    entity_id: media_player.spotify

- alias: "Cube: start music by throwing the cube"
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: lumi_sensor_cube_aqgl01_11
  condition:
    condition: template
    value_template: >
      {{ trigger.event.data.event == 7008 }}
  action:
    service: input_boolean.turn_on
    entity_id: input_boolean.start_the_music

- alias: "Cube: change volume by rotating cube"
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: mi_magic_cube
  condition:
    condition: state
    entity_id: input_select.cube_mode
    state: "Volume"
  action:
    - service: media_player.volume_set
      entity_id:  media_player.kef
      data_template:  # 90 deg is 10%
        volume_level: >
          {% set max_change = 0.15 %}
          {% set dV = [trigger.event.data.event / 100 / 900, max_change] | min %}
          {{ (states.media_player.kef.attributes.volume_level + dV)|round(2) }}
    - service: notify.tv
      data:
        message: >
          Volume set to {{ state_attr("media_player.kef", "volume_level") }}

- alias: "Cube: shuffle Spotify song by shaking cube"
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: lumi_sensor_cube_aqgl01_11
  condition:
    condition: and
    conditions:
      - condition: template
        value_template: >
          {{ trigger.event.data.event == 7007 }}
      - condition: template
        value_template: >
          {{ is_state_attr("media_player.spotify", "source", "LS50 Wireless 00C437")}}
  action:
    - service: media_player.shuffle_set
      entity_id: media_player.spotify
      data:
        shuffle: true
    - service: media_player.media_next_track
      entity_id: media_player.spotify

- alias: "Cube: pause and play Spotify song by tapping cube on side 1"
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: lumi_sensor_cube_aqgl01_11
  condition:
    condition: and
    conditions:
      - condition: template
        value_template: >
          {{ trigger.event.data.event == 1001 }}
      - condition: template
        value_template: >
          {{ is_state_attr("media_player.spotify", "source", "LS50 Wireless 00C437")}}
  action:
    service: media_player.media_play_pause
    entity_id: media_player.spotify

- alias: "Cube: start music by throwing the cube"
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: lumi_sensor_cube_aqgl01_11
  condition:
    condition: template
    value_template: >
      {{ trigger.event.data.event == 7008 }}
  action:
    service: input_boolean.turn_on
    entity_id: input_boolean.start_the_music
