---
#-
#                  _        _
#   ___ _   _ _ __| |_ __ _(_)_ __  ___
#  / __| | | | '__| __/ _` | | '_ \/ __|
# | (__| |_| | |  | || (_| | | | | \__ \
#  \___|\__,_|_|   \__\__,_|_|_| |_|___/
#
#
#- from github.com/tmttn/home-assistant-config
- alias: "Curtains: open the screens"
  trigger:
    - platform: numeric_state
      entity_id: sun.sun
      attribute: elevation
      below: 1
    - platform: numeric_state
      entity_id: sensor.bunderhome_weerstation_ws_2902c_event_rain
      above: 0
    - platform: numeric_state
      entity_id: sensor.bunderhome_weerstation_ws_2902c_uv_index
      below: 1
  action:
    - service: cover.open_cover
      entity_id: cover.curtain_controller_curtain

- alias: "Curtains: close the screens"
  trigger:
    - platform: numeric_state
      entity_id: sensor.bunderhome_weerstation_ws_2902c_uv_index
      above: 2
  condition:
    - condition: numeric_state
      entity_id: sun.sun
      attribute: elevation
      above: 10
    - condition: numeric_state
      entity_id: sensor.bunderhome_weerstation_ws_2902c_event_rain
      below: 1
  action:
    - service: cover.close_cover
      entity_id: cover.curtain_controller_curtain
