---
#-
#      _                  _          _ _
#   __| | ___   ___  _ __| |__   ___| | |
#  / _` |/ _ \ / _ \| '__| '_ \ / _ \ | |
# | (_| | (_) | (_) | |  | |_) |  __/ | |
#  \__,_|\___/ \___/|_|  |_.__/ \___|_|_|
#
#
#- from github.com/tmttn/home-assistant-config
- alias: "Doorbell: the doorbell has been pressed"
  trigger:
    platform: state
    entity_id: binary_sensor.doorbell_ding
    from: "off"
    to: "on"
  action:
    - service: light.turn_on
      data:
        flash: "short"
        entity_id: all
    - service: notify.all_iphones
      data:
        title: "Doorbell"
        message: "Someone in front of the door!"
    - service: tts.google_translate_say
      data:
        entity_id: media_player.google_home
        language: nl
        message: Er is iemand aan de voordeur.

- alias: "Doorbell: stream doorbell to the TV"
  trigger:
    platform: state
    entity_id: binary_sensor.doorbell_ding
    from: "off"
    to: "on"
  condition: "{{ is_state('media_player.tv', 'on') }}"
  action:
    - service: camera.play_stream
      data:
        media_player: media_player.shield
      target:
        entity_id: camera.front_door_video
