---
#-
#      _                  _          _ _
#   __| | ___   ___  _ __| |__   ___| | |
#  / _` |/ _ \ / _ \| '__| '_ \ / _ \ | |
# | (_| | (_) | (_) | |  | |_) |  __/ | |
#  \__,_|\___/ \___/|_|  |_.__/ \___|_|_|
#
#
#- from github.com/tmttn/home-assistant-config
- alias: "Doorbell: the doorbell has been pressed"
  id: "doorbell_the-doorbell-has-been-pressed"
  trigger:
    platform: state
    entity_id: binary_sensor.doorbell_ding
    from: "off"
    to: "on"
  action:
    - service: light.turn_on
      data:
        flash: "short"
        entity_id:
          - light.living_room_lights
          - light.kitchen_lights
    - service: notify.all_iphones
      data:
        title: "Doorbell"
        message: "Someone in front of the door!"
    - service: tts.google_translate_say
      data:
        entity_id: media_player.google_home
        language: nl
        message: Er is iemand aan de voordeur.
