---
#-
#      _                  _          _ _
#   __| | ___   ___  _ __| |__   ___| | |
#  / _` |/ _ \ / _ \| '__| '_ \ / _ \ | |
# | (_| | (_) | (_) | |  | |_) |  __/ | |
#  \__,_|\___/ \___/|_|  |_.__/ \___|_|_|
#
#
#- from github.com/basnijholt/home-assistant-config
- alias: "Doorbell: click the button"
  initial_state: "on"
  trigger:
    platform: event
    event_type: zha_event
    event_data:
      device_ieee: "00:15:8d:00:02:32:f1:f4" # smart_switch_doorbell
      command: "single" # Single click
  action:
    - service: light.turn_on
      data:
        flash: "short"
        entity_id: all
    - service: notify.all_iphones
      data:
        title: "Doorbell"
        message: "Someone in front of the door!"
    - condition: state
      entity_id: media_player.tv
      state: "on"
    - service: notify.tv
      data:
        message: "Someone in front of the door!"
