---
#-
#      _                  _          _ _
#   __| | ___   ___  _ __| |__   ___| | |
#  / _` |/ _ \ / _ \| '__| '_ \ / _ \ | |
# | (_| | (_) | (_) | |  | |_) |  __/ | |
#  \__,_|\___/ \___/|_|  |_.__/ \___|_|_|
#
#
#- from github.com/tmttn/home-assistant-config
- alias: "Doorbell: flash the lights when the doorbell rings"
  trigger:
    platform: state
    entity_id: binary_sensor.doorbell_ding
    from: "off"
    to: "on"
  action:
    - service: light.turn_on
      data:
        flash: "short"
        entity_id: all
    - service: notify.all_iphones
      data:
        title: "Doorbell"
        message: "Someone in front of the door!"
