---
- alias: "Frontend: turn on dark mode"
  trigger:
    platform: time
    at: "20:00"
  action:
    entity_id: input_boolean.dark_mode
    service: input_boolean.turn_on

- alias: "Frontend: turn on light mode"
  trigger:
    platform: time
    at: "06:00"
  action:
    entity_id: input_boolean.dark_mode
    service: input_boolean.turn_off

- alias: "Frontend: change theme"
  trigger:
    - platform: state
      entity_id: input_select.theme
    - platform: state
      entity_id: input_boolean.dark_mode
    - platform: homeassistant
      event: start
  action:
    service: frontend.set_theme
    data_template:
      name: >
        {% if is_state("input_boolean.dark_mode", "on") %}
          ios-dark-mode-{{ states("input_select.theme") }}
        {% else %}
          ios-light-mode-{{ states("input_select.theme") }}
        {% endif %}
