---
- alias: "Guest mode: toggle on or off"
  initial_state: "on"
  trigger:
    platform: state
    entity_id: input_boolean.guest_mode
  action:
    service_template:
      automation.turn_{{ "off" if trigger.to_state.state == "on" else "on"}}
    entity_id: group.guest_mode
