---
- alias: "iMac volume: ensure max 1 input_boolean is on"
  trigger:
    - platform: state
      entity_id: input_boolean.imac_volume_0
      from: "off"
      to: "on"
    - platform: state
      entity_id: input_boolean.imac_volume_1
      from: "off"
      to: "on"
    - platform: state
      entity_id: input_boolean.imac_volume_2
      from: "off"
      to: "on"
    - platform: state
      entity_id: input_boolean.imac_volume_3
      from: "off"
      to: "on"
    - platform: state
      entity_id: input_boolean.imac_volume_4
      from: "off"
      to: "on"
    - platform: state
      entity_id: input_boolean.imac_volume_5
      from: "off"
      to: "on"
    - platform: state
      entity_id: input_boolean.imac_volume_6
      from: "off"
      to: "on"
    - platform: state
      entity_id: input_boolean.imac_volume_7
      from: "off"
      to: "on"
    - platform: state
      entity_id: input_boolean.imac_volume_8
      from: "off"
      to: "on"
    - platform: state
      entity_id: input_boolean.imac_volume_9
      from: "off"
      to: "on"
    - platform: state
      entity_id: input_boolean.imac_volume_10
      from: "off"
      to: "on"
  action:
    - service: input_boolean.turn_off
      data_template:
        entity_id: >
          {% set x = trigger.entity_id[-1]|int %}
          {%- for i in range(11) -%}
            {%- if x != i -%}
              input_boolean.imac_volume_{{ i }}{%- if not loop.last %},{%- endif %}
            {%- endif -%}
          {%- endfor -%}
    - service: media_player.volume_set
      entity_id:  media_player.bedroom_speakers
      data_template:
        volume_level: >
          {{ trigger.entity_id[-1]|float / 10 }}
