---
#-
#  _         __      _
# | | _____ / _|  __| |___ _ __
# | |/ / _ \ |_  / _` / __| '_ \
# |   <  __/  _|| (_| \__ \ |_) |
# |_|\_\___|_|___\__,_|___/ .__/
#           |_____|       |_|
#
#- from github.com/basnijholt/home-assistant-config

#   _                   _                             _
#  (_)_ __  _ __  _   _| |_     _ __  _   _ _ __ ___ | |__   ___ _ __
#  | | '_ \| '_ \| | | | __|   | '_ \| | | | '_ ` _ \| '_ \ / _ \ '__|
#  | | | | | |_) | |_| | |_    | | | | |_| | | | | | | |_) |  __/ |
#  |_|_| |_| .__/ \__,_|\__|___|_| |_|\__,_|_| |_| |_|_.__/ \___|_|
#          |_|            |_____|

- alias: "KEF DSP: sync desk_db"
  trigger:
    - platform: state
      entity_id: media_player.kef_ls50
      attribute: desk_db
    - platform: state
      entity_id: input_number.kef_ls50_desk_db
  action:
    service: script.sync_kef_dsp
    data:
      name: kef_ls50
      domain: number
      trigger_entity_id: "{{ trigger.entity_id }}"
      attribute: desk_db

- alias: "KEF DSP: sync wall_db"
  trigger:
    - platform: state
      entity_id: media_player.kef_ls50
      attribute: wall_db
    - platform: state
      entity_id: input_number.kef_ls50_wall_db
  action:
    service: script.sync_kef_dsp
    data:
      name: kef_ls50
      domain: number
      trigger_entity_id: "{{ trigger.entity_id }}"
      attribute: "wall_db"

- alias: "KEF DSP: sync treble_db"
  trigger:
    - platform: state
      entity_id: media_player.kef_ls50
      attribute: treble_db
    - platform: state
      entity_id: input_number.kef_ls50_treble_db
  action:
    service: script.sync_kef_dsp
    data:
      name: kef_ls50
      domain: number
      trigger_entity_id: "{{ trigger.entity_id }}"
      attribute: "treble_db"

- alias: "KEF DSP: sync high_hz"
  trigger:
    - platform: state
      entity_id: media_player.kef_ls50
      attribute: high_hz
    - platform: state
      entity_id: input_number.kef_ls50_high_hz
  action:
    service: script.sync_kef_dsp
    data:
      name: kef_ls50
      domain: number
      trigger_entity_id: "{{ trigger.entity_id }}"
      attribute: "high_hz"

- alias: "KEF DSP: sync low_hz"
  trigger:
    - platform: state
      entity_id: media_player.kef_ls50
      attribute: low_hz
    - platform: state
      entity_id: input_number.kef_ls50_low_hz
  action:
    service: script.sync_kef_dsp
    data:
      name: kef_ls50
      domain: number
      trigger_entity_id: "{{ trigger.entity_id }}"
      attribute: "low_hz"

- alias: "KEF DSP: sync sub_db"
  trigger:
    - platform: state
      entity_id: media_player.kef_ls50
      attribute: sub_db
    - platform: state
      entity_id: input_number.kef_ls50_sub_db
  action:
    service: script.sync_kef_dsp
    data:
      name: kef_ls50
      domain: number
      trigger_entity_id: "{{ trigger.entity_id }}"
      attribute: "sub_db"

#   _                   _                _           _
#  (_)_ __  _ __  _   _| |_     ___  ___| | ___  ___| |_
#  | | '_ \| '_ \| | | | __|   / __|/ _ \ |/ _ \/ __| __|
#  | | | | | |_) | |_| | |_    \__ \  __/ |  __/ (__| |_
#  |_|_| |_| .__/ \__,_|\__|___|___/\___|_|\___|\___|\__|
#          |_|            |_____|

- alias: "KEF DSP: sync sub_polarity"
  trigger:
    - platform: state
      entity_id: media_player.kef_ls50
      attribute: sub_polarity
    - platform: state
      entity_id: input_select.kef_ls50_sub_polarity
  action:
    service: script.sync_kef_dsp
    data:
      name: kef_ls50
      domain: select
      trigger_entity_id: "{{ trigger.entity_id }}"
      attribute: "sub_polarity"

- alias: "KEF DSP: sync bass_extension"
  trigger:
    - platform: state
      entity_id: media_player.kef_ls50
      attribute: bass_extension
    - platform: state
      entity_id: input_select.kef_ls50_bass_extension
  action:
    service: script.sync_kef_dsp
    data:
      name: kef_ls50
      domain: select
      trigger_entity_id: "{{ trigger.entity_id }}"
      attribute: "bass_extension"

#   _                   _       _                 _
#  (_)_ __  _ __  _   _| |_    | |__   ___   ___ | | ___  __ _ _ __
#  | | '_ \| '_ \| | | | __|   | '_ \ / _ \ / _ \| |/ _ \/ _` | '_ \
#  | | | | | |_) | |_| | |_    | |_) | (_) | (_) | |  __/ (_| | | | |
#  |_|_| |_| .__/ \__,_|\__|___|_.__/ \___/ \___/|_|\___|\__,_|_| |_|
#          |_|            |_____|

- alias: "KEF DSP: sync desk_mode"
  trigger:
    - platform: state
      entity_id: media_player.kef_ls50
      attribute: desk_mode
    - platform: state
      entity_id: input_boolean.kef_ls50_desk_mode
  action:
    service: script.sync_kef_dsp
    data:
      name: kef_ls50
      domain: boolean
      trigger_entity_id: "{{ trigger.entity_id }}"
      attribute: "desk_mode"

- alias: "KEF DSP: sync wall_mode"
  trigger:
    - platform: state
      entity_id: media_player.kef_ls50
      attribute: wall_mode
    - platform: state
      entity_id: input_boolean.kef_ls50_wall_mode
  action:
    service: script.sync_kef_dsp
    data:
      name: kef_ls50
      domain: boolean
      trigger_entity_id: "{{ trigger.entity_id }}"
      attribute: "wall_mode"

- alias: "KEF DSP: sync phase_correction"
  trigger:
    - platform: state
      entity_id: media_player.kef_ls50
      attribute: phase_correction
    - platform: state
      entity_id: input_boolean.kef_ls50_phase_correction
  action:
    service: script.sync_kef_dsp
    data:
      name: kef_ls50
      domain: boolean
      trigger_entity_id: "{{ trigger.entity_id }}"
      attribute: "phase_correction"

- alias: "KEF DSP: sync high_pass"
  trigger:
    - platform: state
      entity_id: media_player.kef_ls50
      attribute: high_pass
    - platform: state
      entity_id: input_boolean.kef_ls50_high_pass
  action:
    service: script.sync_kef_dsp
    data:
      name: kef_ls50
      domain: boolean
      trigger_entity_id: "{{ trigger.entity_id }}"
      attribute: "high_pass"
