---
#-
#  _         __      _
# | | _____ / _|  __| |___ _ __
# | |/ / _ \ |_  / _` / __| '_ \
# |   <  __/  _|| (_| \__ \ |_) |
# |_|\_\___|_|___\__,_|___/ .__/
#           |_____|       |_|
#
#- from github.com/basnijholt/home-assistant-config

# input_number

- alias: "KEF DSP: sync desk_db"
  trigger:
    - platform: state
      entity_id: media_player.kef_ls50
    - platform: state
      entity_id: input_number.kef_ls50_desk_db
  action:
    service: script.sync_kef_dsp
    data_template:
      name: kef_ls50
      domain: number
      trigger_entity_id: "{{ trigger.entity_id }}"
      trigger_to_state: "{{ trigger.to_state.state }}"
      attribute: desk_db
      type: float

- alias: "KEF DSP: sync wall_db"
  trigger:
    - platform: state
      entity_id: media_player.kef_ls50
    - platform: state
      entity_id: input_number.kef_ls50_wall_db
  action:
    service: script.sync_kef_dsp
    data_template:
      name: kef_ls50
      domain: number
      trigger_entity_id: "{{ trigger.entity_id }}"
      trigger_to_state: "{{ trigger.to_state.state }}"
      attribute: "wall_db"
      type: float

- alias: "KEF DSP: sync treble_db"
  trigger:
    - platform: state
      entity_id: media_player.kef_ls50
    - platform: state
      entity_id: input_number.kef_ls50_treble_db
  action:
    service: script.sync_kef_dsp
    data_template:
      name: kef_ls50
      domain: number
      trigger_entity_id: "{{ trigger.entity_id }}"
      trigger_to_state: "{{ trigger.to_state.state }}"
      attribute: "treble_db"
      type: float

- alias: "KEF DSP: sync high_hz"
  trigger:
    - platform: state
      entity_id: media_player.kef_ls50
    - platform: state
      entity_id: input_number.kef_ls50_high_hz
  action:
    service: script.sync_kef_dsp
    data_template:
      name: kef_ls50
      domain: number
      trigger_entity_id: "{{ trigger.entity_id }}"
      trigger_to_state: "{{ trigger.to_state.state }}"
      attribute: "high_hz"
      type: int

- alias: "KEF DSP: sync low_hz"
  trigger:
    - platform: state
      entity_id: media_player.kef_ls50
    - platform: state
      entity_id: input_number.kef_ls50_low_hz
  action:
    service: script.sync_kef_dsp
    data_template:
      name: kef_ls50
      domain: number
      trigger_entity_id: "{{ trigger.entity_id }}"
      trigger_to_state: "{{ trigger.to_state.state }}"
      attribute: "low_hz"
      type: int

- alias: "KEF DSP: sync sub_db"
  trigger:
    - platform: state
      entity_id: media_player.kef_ls50
    - platform: state
      entity_id: input_number.kef_ls50_sub_db
  action:
    service: script.sync_kef_dsp
    data_template:
      name: kef_ls50
      domain: number
      trigger_entity_id: "{{ trigger.entity_id }}"
      trigger_to_state: "{{ trigger.to_state.state }}"
      attribute: "sub_db"
      type: int

# input_selects

- alias: "KEF DSP: sync sub_polarity"
  trigger:
    - platform: state
      entity_id: media_player.kef_ls50
    - platform: state
      entity_id: input_select.kef_ls50_sub_polarity
  action:
    service: script.sync_kef_dsp
    data_template:
      name: kef_ls50
      domain: select
      trigger_entity_id: "{{ trigger.entity_id }}"
      trigger_to_state: "{{ trigger.to_state.state }}"
      attribute: "sub_polarity"

- alias: "KEF DSP: sync bass_extension"
  trigger:
    - platform: state
      entity_id: media_player.kef_ls50
    - platform: state
      entity_id: input_select.kef_ls50_bass_extension
  action:
    service: script.sync_kef_dsp
    data_template:
      name: kef_ls50
      domain: select
      trigger_entity_id: "{{ trigger.entity_id }}"
      trigger_to_state: "{{ trigger.to_state.state }}"
      attribute: "bass_extension"


# input_booleans

- alias: "KEF DSP: sync desk_mode"
  trigger:
    - platform: state
      entity_id: media_player.kef_ls50
    - platform: state
      entity_id: input_boolean.kef_ls50_desk_mode
  action:
    service: script.sync_kef_dsp
    data_template:
      name: kef_ls50
      domain: boolean
      trigger_entity_id: "{{ trigger.entity_id }}"
      trigger_to_state: "{{ trigger.to_state.state }}"
      attribute: "desk_mode"

- alias: "KEF DSP: sync wall_mode"
  trigger:
    - platform: state
      entity_id: media_player.kef_ls50
    - platform: state
      entity_id: input_boolean.kef_ls50_wall_mode
  action:
    service: script.sync_kef_dsp
    data_template:
      name: kef_ls50
      domain: boolean
      trigger_entity_id: "{{ trigger.entity_id }}"
      trigger_to_state: "{{ trigger.to_state.state }}"
      attribute: "wall_mode"

- alias: "KEF DSP: sync phase_correction"
  trigger:
    - platform: state
      entity_id: media_player.kef_ls50
    - platform: state
      entity_id: input_boolean.kef_ls50_phase_correction
  action:
    service: script.sync_kef_dsp
    data_template:
      name: kef_ls50
      domain: boolean
      trigger_entity_id: "{{ trigger.entity_id }}"
      trigger_to_state: "{{ trigger.to_state.state }}"
      attribute: "phase_correction"

- alias: "KEF DSP: sync high_pass"
  trigger:
    - platform: state
      entity_id: media_player.kef_ls50
    - platform: state
      entity_id: input_boolean.kef_ls50_high_pass
  action:
    service: script.sync_kef_dsp
    data_template:
      name: kef_ls50
      domain: boolean
      trigger_entity_id: "{{ trigger.entity_id }}"
      trigger_to_state: "{{ trigger.to_state.state }}"
      attribute: "high_pass"
