---
- alias: "Leaving: turn off everything"
  initial_state: "on"
  trigger:
    platform: state
    entity_id: group.persons
    from: home
    to: not_home
    for:
      minutes: 30
  action:
    - service: scene.turn_on
      entity_id: scene.bed_time
    - service: notify.mobile_app_basnijholt_iphone
      data:
        title: "Leaving"
        message: "Everything automatically turned off!"
