---
- alias: "Leaving: automatically turn off everything"
  initial_state: "on"
  trigger:
    - platform: state
      entity_id: binary_sensor.someone_in_the_house_in_last_hour
      from: "on"
      to: "off"
    - platform: time_pattern
      hours: "/1"
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: binary_sensor.someone_in_the_house_in_last_hour
        state: "off"
      - condition: or
        conditions:
          - condition: state
            entity_id: group.all_lights
            state: "on"
          - condition: state
            entity_id: media_player.kef
            state: "on"
          - condition: state
            entity_id: media_player.tv
            state: "on"
  action:
    - service: light.turn_off
      entity_id: all
    - service: media_player.turn_off
      entity_id: media_player.kef
    - service: media_player.turn_off
      entity_id: media_player.tv
    - service: notify.mobile_app_basnijholt_iphone
      data:
        title: "Leaving"
        message: "Everything automatically turned off!"

- alias: "Leaving: manually turn off everything"
  initial_state: "on"
  trigger:
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: smart_switch_downstairs
      event: 1002
  action:
    # - service: light.turn_on  # XXX: did not install these lights yet
    #   data:
    #     flash: "short"
    #     entity_id: light.stairs_down
    - service: script.turn_off_everything
    - service: notify.mobile_app_basnijholt_iphone
      data:
        title: "Leaving"
        message: "Everything turned off, see you soon! ❤️"
