---
#-
#  _                  _
# | | ___  __ ___   _(_)_ __   __ _
# | |/ _ \/ _` \ \ / / | '_ \ / _` |
# | |  __/ (_| |\ V /| | | | | (_| |
# |_|\___|\__,_| \_/ |_|_| |_|\__, |
#                             |___/
#
#- from github.com/basnijholt/home-assistant-config

- alias: "Leaving: automatically turn off everything"
  initial_state: "on"
  trigger:
    - platform: state
      entity_id: binary_sensor.someone_in_the_house_in_last_hour
      from: "on"
      to: "off"
      for: "00:01:00"
    - platform: time_pattern
      hours: "/1"
  condition:
    - condition: state
      entity_id:
        - binary_sensor.no_one_home
        - binary_sensor.anything_on
      state: "on"
    - condition: state
      entity_id:
        - binary_sensor.someone_in_the_house_in_last_hour
        - input_boolean.guest_mode
      state: "off"
  action:
    - service: script.leaving
    - service: notify.all_iphones
      data:
        title: "Leaving"
        message: "Everything automatically turned off!"

- alias: "Leaving: ask to turn off everything"
  initial_state: "on"
  trigger:
    - platform: state
      entity_id: person.bas
      from: "home"
    - platform: state
      entity_id: person.marcella
      from: "home"
  condition:
    - condition: state
      entity_id:
        - binary_sensor.no_one_home
        - binary_sensor.anything_on
      state: "on"
    - condition: state
      entity_id: input_boolean.guest_mode
      state: "off"
  action:
    - delay: "00:05:00" # something still needs to be on in 5 min
    - condition: state
      entity_id: binary_sensor.no_one_home
      state: "on"
    - service: notify.all_iphones
      data:
        message: "No one is home, turn off everything?"
        data:
          push:
            category: turn_off_everything

- alias: "Leaving: turn off everything after notification"
  trigger:
    platform: event
    event_type: ios.notification_action_fired
    event_data:
      actionName: TURN_OFF_EVERYTHING
  action:
    service: script.leaving


- alias: "Leaving: downstairs Aqara Wireless Mini Switch"
  trigger:
    platform: event
    event_type: zha_event
    event_data:
      device_ieee: "00:15:8d:00:02:33:38:62" # smart_switch_downstairs
      command: "single"  # single click
  action:
    - wait_for_trigger:  # when the door closes, turn off everything
        platform: state
        entity_id: binary_sensor.openclose_front_door
        from: "on"
        to: "off"
      timeout: "00:01:00"
      continue_on_timeout: false
    - service: script.turn_off_everything
    - service: notify.all_iphones
      data:
        title: "Bye 👋"
        message: "See you soon!"
