---
- alias: "Leaving: automatically turn off everything"
  initial_state: "on"
  trigger:
    - platform: state
      entity_id: binary_sensor.someone_in_the_house_in_last_hour
      from: "on"
      to: "off"
    - platform: time_pattern
      hours: "/1"
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: binary_sensor.someone_in_the_house_in_last_hour
        state: "off"
      - condition: state
        entity_id: input_boolean.guest_mode
        state: "off"
      - condition: or
        conditions:
          - condition: state
            entity_id: group.all_lights
            state: "on"
          - condition: state
            entity_id: media_player.kef
            state: "on"
          - condition: state
            entity_id: media_player.tv
            state: "on"
  action:
    - service: light.turn_off
      entity_id: all
    - service: media_player.turn_off
      entity_id: media_player.kef
    - service: media_player.turn_off
      entity_id: media_player.tv
    - service: notify.mobile_app_basnijholt_iphone
      data:
        title: "Leaving"
        message: "Everything automatically turned off!"

- alias: "Leaving: manually turn off everything"
  initial_state: "on"
  trigger:
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: smart_switch_downstairs
      event: 1002
  action:
    # - service: light.turn_on  # XXX: did not install these lights yet
    #   data:
    #     flash: "short"
    #     entity_id: light.stairs_down
    - service: script.turn_off_everything
    - service: notify.mobile_app_basnijholt_iphone
      data:
        title: "Leaving"
        message: "Everything turned off, see you soon! ❤️"

- alias: "Arriving: turn on music and cozy lights"
  initial_state: "on"
  trigger:
  trigger:
    - platform: event
      event_type: deconz_event
      event_data:
        id: smart_switch_downstairs
        event: 1004
  action:
    - service: light.turn_on
      entity_id: light.living_room_lights
      data:
        brightness: 100
    - service: script.turn_on
      entity_id: script.cozy_lights_living_room
    - service: script.start_spotify
      data_template:
        source: LS50 Wireless 00C437
        playlist: '{{ states("sensor.favorite_playlist_of_nearest_person") }}'
        volume: 0.25

# XXX: turn off in guest mode
- alias: "Arriving: switch music from iPhone to speakers if no one is home"
  trigger:
    platform: state
    entity_id: binary_sensor.openclose_front_door
    from: "off"
    to: "on"
  condition:
    - condition: state
      entity_id: persons.marcella
      state: not_home
    - condition: template
      value_template: >
        {{ state_attr("media_player.spotify", "source") == "basnijholt-iphone"
           and states("media_player.spotify") == "playing" }}
  action:
    - service: media_player.turn_on
      entity_id: media_player.kef
    - service: media_player.select_source
      entity_id: media_player.kef
      data:
        source: Wifi
    - service: media_player.select_source
      entity_id: media_player.spotify
      data:
        source: LS50 Wireless 00C437
