---
- alias: "Leaving: automatically turn off everything"
  initial_state: "on"
  trigger:
    - platform: state
      entity_id: binary_sensor.someone_in_the_house_in_last_hour
      from: "on"
      to: "off"
    - platform: time_pattern
      hours: "/1"
  condition:
    - condition: state
      entity_id: binary_sensor.someone_in_the_house_in_last_hour
      state: "off"
    - condition: state
      entity_id: input_boolean.guest_mode
      state: "off"
    - condition: state
      entity_id: binary_sensor.anything_on
      state: "on"
  action:
    - service: script.turn_off_everything
    - service: notify.mobile_app_basnijholt_iphone
      data:
        title: "Leaving"
        message: "Everything automatically turned off!"

- alias: "Leaving: ask to turn off everything"
  initial_state: "on"
  trigger:
    - platform: state
      entity_id: persons.bas
      from: "home"
      to: "not_home"
    - platform: state
      entity_id: persons.marcella
      from: "home"
      to: "not_home"
  condition:
    - condition: template
      value_template: >
        {{ not is_state("person.bas", "home")
           and not is_state("person.marcella", "home") }}
    - condition: state
      entity_id: input_boolean.guest_mode
      state: "off"
    - condition: state
      entity_id: binary_sensor.anything_on
      state: "on"
  action:
    service: notify.mobile_app_basnijholt_iphone
    data:
      message: "No one is home, turn off everything?"
      data:
        push:
          category: turn_off_everything

- alias: "Leaving: turn off everything after notification"
  trigger:
    platform: event
    event_type: ios.notification_action_fired
    event_data:
      actionName: TURN_OFF_EVERYTHING
  action:
    service: script.turn_off_everything

- alias: "Leaving: single click to turn off everything"
  initial_state: "on"
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: smart_switch_downstairs
      event: 1002
  action:
    - service: light.turn_on
      data:
        flash: "short"
        entity_id: light.stairs_down
    - service: script.turn_off_everything_non_automatic
    - service: notify.mobile_app_basnijholt_iphone
      data:
        title: "Leaving"
        message: "Everything turned off, see you soon! ❤️"

- alias: "Arriving: double click to turn on music and cozy lights"
  initial_state: "on"
  trigger:
    - platform: event
      event_type: deconz_event
      event_data:
        id: smart_switch_downstairs
        event: 1004
  action:
    - service: light.turn_on
      entity_id: light.living_room_lights
      data:
        brightness: 100
    - service: script.cozy_lights_living_room
    - service: script.start_spotify
      data_template:
        source: LS50 Wireless
        playlist: '{{ states("sensor.favorite_playlist_of_nearest_person") }}'
        volume: 0.25

- alias: "Arriving: switch music from iPhone to speakers if no one is home"
  trigger:
    platform: state
    entity_id: binary_sensor.openclose_front_door
    from: "off"
    to: "on"
  condition:
    - condition: state
      entity_id: persons.marcella
      state: not_home
    - condition: state
      entity_id: input_boolean.guest_mode
      state: "off"
    - condition: template
      value_template: >
        {{ is_state_attr("media_player.spotify", "source", "basnijholt-iphone")
           and is_state("media_player.spotify", "playing") }}
  action:
    - service: media_player.turn_on
      entity_id: media_player.kef
    - service: media_player.select_source
      entity_id: media_player.kef
      data:
        source: Wifi
    - service: media_player.select_source
      entity_id: media_player.spotify
      data:
        source: LS50 Wireless
