---
#-
#  _                  _
# | | ___  __ ___   _(_)_ __   __ _
# | |/ _ \/ _` \ \ / / | '_ \ / _` |
# | |  __/ (_| |\ V /| | | | | (_| |
# |_|\___|\__,_| \_/ |_|_| |_|\__, |
#                             |___/
#
#- from github.com/basnijholt/home-assistant-config

- alias: "Leaving: automatically turn off everything"
  initial_state: "on"
  trigger:
    - platform: state
      entity_id: binary_sensor.someone_in_the_house_in_last_hour
      from: "on"
      to: "off"
    - platform: time_pattern
      hours: "/1"
  condition:
    - condition: state
      entity_id: binary_sensor.no_one_home
      state: "on"
    - condition: state
      entity_id: binary_sensor.someone_in_the_house_in_last_hour
      state: "off"
    - condition: state
      entity_id: input_boolean.guest_mode
      state: "off"
    - condition: state
      entity_id: binary_sensor.anything_on
      state: "on"
  action:
    - service: script.leaving
    - service: notify.all_iphones
      data:
        title: "Leaving"
        message: "Everything automatically turned off!"

- alias: "Leaving: ask to turn off everything"
  initial_state: "on"
  trigger:
    - platform: state
      entity_id: persons.bas
    - platform: state
      entity_id: persons.marcella
  condition:
    - condition: state
      entity_id: binary_sensor.no_one_home
      state: "on"
    - condition: state
      entity_id: input_boolean.guest_mode
      state: "off"
    - condition: state
      entity_id: binary_sensor.anything_on
      state: "on"
  action:
    service: notify.all_iphones
    data:
      message: "No one is home, turn off everything?"
      data:
        push:
          category: turn_off_everything

- alias: "Leaving: turn off everything after notification"
  trigger:
    platform: event
    event_type: ios.notification_action_fired
    event_data:
      actionName: TURN_OFF_EVERYTHING
  action:
    - service: script.leaving

- alias: "Leaving: single click to turn off everything"
  initial_state: "on"
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: smart_switch_downstairs
      event: 1002  # Single click
  action:
    - service: light.turn_on
      data:
        flash: "short"
        entity_id: light.stairs_down
    - service: script.turn_off_everything_non_automatic
    - service: script.set_low_temperature
    - service_template: >
        {{ states("sensor.nearest_iphone_notify") }}
      data:
        title: "Leaving"
        message: "Everything turned off, see you soon! ❤️"
