---
# XXX: not installed currently
# - alias: "Light: copy light"
#   trigger:  # two triggers, to avoid triggering on "unavailable"
#     - platform: state
#       entity_id: sensor.desk_lamp_current
#       from: "on"
#       to: "off"
#     - platform: state
#       entity_id: sensor.desk_lamp_current
#       from: "off"
#       to: "on"
#   action:
#     service_template: switch.turn_{{ trigger.to_state.state }}
#     entity_id: switch.light2

# XXX: fix the switches first
# - alias: "Light: turn on when coming home"
#   trigger:
#     - platform: state
#       entity_id: group.persons
#       from: not_home
#       to: home
#     - platform: state
#       entity_id: binary_sensor.openclose_1  # XXX: didn't attach this yet!
#       from: "off"
#       to: "on"
#   condition:
#     condition: sun
#     after: sunset
#     after_offset: "-0:30:00"
#   action:
#     service: light.turn_on
#     entity_id: light.ceiling_hall

- alias: "Light: turn on night lights with button single click"
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: smart_switch_1
  condition:
    condition: template
    value_template: >
      {{ trigger.event.data.event == 1002 }}
  action:
    service: scene.turn_on
    entity_id: scene.night_lights

- alias: "Light: turn off everything with button double click"
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: smart_switch_1
  condition:
    condition: template
    value_template: >
      {{ trigger.event.data.event == 1004 }}
  action:
    service: scene.turn_on
    entity_id: scene.bed_time

- alias: "Light: turn on kitchen"
  trigger:
    - platform: state
      entity_id: binary_sensor.activity_in_kitchen
  action:
    service_template: light.turn_{{ trigger.to_state.state }}
    entity_id: light.ceiling_kitchen

- alias: "Light: turn on bathroom"
  trigger:
    - platform: state
      entity_id:  binary_sensor.activity_in_bathroom
  action:
    service_template: light.turn_{{ trigger.to_state.state }}
    entity_id: light.ceiling_bathroom

- alias: "Light: turn on toilet"
  trigger:
    - platform: state
      entity_id:  binary_sensor.activity_in_toilet
  action:
    service_template: light.turn_{{ trigger.to_state.state }}
    entity_id: light.toilet

- alias: "Light: change hue of living room lights with cube"
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: mi_magic_cube
  condition:
    condition: state
    entity_id: input_select.cube_mode
    state: "Hue"
  action:
    service: light.turn_on
    entity_id:
      - light.sphere_1
      - light.sphere_2
      - light.corner_living_room
      - light.ceiling_living_room
    data_template:  # 90 deg is 10%
      hs_color:
        - >
           {% set hue, sat = state_attr('light.sphere_1', 'hs_color') %}
           {% set delta = trigger.event.data.event / 900 %}
           {% set new_hue = [([0, (hue + delta)]|max), 360]|min %}
           {{ new_hue|round(3) }}
        - >
           {{ state_attr('light.sphere_1', 'hs_color')[1] }}

- alias: "Light: change brightness of living room lights with cube"
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: mi_magic_cube
  condition:
    condition: state
    entity_id: input_select.cube_mode
    state: "Brightness"
  action:
    service: light.turn_on
    entity_id:
      - light.sphere_1
      - light.sphere_2
      - light.corner_living_room
      - light.ceiling_living_room
    data_template:  # 90 deg is 10%
      brightness: >
        {% set brightness = state_attr('light.sphere_1', 'brightness') %}
        {% set delta = trigger.event.data.event / 900 %}
        {% set new_brightness = [([0, (brightness + delta)]|max), 255]|min %}
        {{ new_brightness|int }}
