---
# XXX: fix the switches first
# - alias: "Light: turn on when coming home"
#   trigger:
#     - platform: state
#       entity_id: group.persons
#       from: not_home
#       to: home
#     - platform: state
#       entity_id: binary_sensor.openclose_1  # XXX: didn't attach this yet!
#       from: "off"
#       to: "on"
#   condition:
#     condition: sun
#     after: sunset
#     after_offset: "-0:30:00"
#   action:
#     service: light.turn_on
    # entity_id:
    #   - group.hall_stairs_lights  # XXX: make this group
    #   - group.hall_lights  # XXX: make this group

- alias: "Light: next colors in the bedroom"
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: smart_switch_1
  condition:
    condition: template
    value_template: >
      {{ trigger.event.data.event == 1004 }}
  action:
    - service: input_select.select_next
      data:
       entity_id: input_select.last_script_bedroom
    - service: script.turn_on
      data_template:
        entity_id: "{{ states('input_select.last_script_bedroom') }}"

- alias: "Light: next colors in the living room"
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: smart_switch_4
  condition:
    condition: template
    value_template: >
      {{ trigger.event.data.event == 1004 }}
  action:
    - service: input_select.select_next
      data:
       entity_id: input_select.last_script_living_room
    - service: script.turn_on
      data_template:
        entity_id: "{{ states('input_select.last_script_living_room') }}"

- alias: "Light: toggle max/min brightness in the bedroom"
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: smart_switch_1
  condition:
    condition: template
    value_template: >
      {{ trigger.event.data.event == 1002 }}
  action:
    - service: script.increase_brightness
      data:
        group: group.bedroom_lights

- alias: "Light: toggle max/min brightness in the living room"
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: smart_switch_4
  condition:
    condition: template
    value_template: >
      {{ trigger.event.data.event == 1002 }}
  action:
    - service: script.increase_brightness
      data:
        group: group.living_room_lights

- alias: "Light: turn on kitchen"
  trigger:
    - platform: state
      entity_id: binary_sensor.activity_in_kitchen
  action:
    service_template: light.turn_{{ trigger.to_state.state }}
    entity_id: light.ceiling_kitchen

- alias: "Light: turn on bathroom"
  trigger:
    - platform: state
      entity_id:  binary_sensor.activity_in_bathroom
  action:
    service_template: light.turn_{{ trigger.to_state.state }}
    entity_id: light.ceiling_bathroom

- alias: "Light: turn on toilet"
  trigger:
    - platform: state
      entity_id:  binary_sensor.activity_in_toilet
  action:
    service_template: light.turn_{{ trigger.to_state.state }}
    entity_id: light.toilet

# XXX: no not have the sensor yet!
# - alias: "Light: turn on bedroom"
#   trigger:
#     - platform: state
#       entity_id:  binary_sensor.activity_in_bedroom  # XXX: ADD THIS SENSOR
#   condition:
#     condition: state
#     entity_id: input_boolean.sleep_mode
#     state: "on"
#   action:
#     service_template: light.turn_{{ trigger.to_state.state }}
#     entity_id: group.bedroom_lights

- alias: "Light: change hue of living room lights with cube"
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: mi_magic_cube
  condition:
    condition: state
    entity_id: input_select.cube_mode
    state: "Hue"
  action:
    service: light.turn_on
    entity_id: group.living_room_lights
    data_template:
      hs_color:
        - >
           {% set hue, sat = state_attr('light.sphere_1', 'hs_color') %}
           {% set delta = trigger.event.data.event / 450 %}
           {% set new_hue = [([0, (hue + delta)]|max), 360]|min %}
           {{ new_hue|round(3) }}
        - >
           {{ state_attr('light.sphere_1', 'hs_color')[1] }}

- alias: "Light: change brightness of living room lights with cube"
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: mi_magic_cube
  condition:
    condition: state
    entity_id: input_select.cube_mode
    state: "Brightness"
  action:
    service: light.turn_on
    entity_id: group.living_room_lights
    data_template:
      brightness: >
        {% set brightness = state_attr('light.sphere_1', 'brightness') %}
        {% set delta = trigger.event.data.event / 450 %}
        {% set new_brightness = [([0, (brightness + delta)]|max), 255]|min %}
        {{ new_brightness|int }}
