---
- alias: "Light: next colors in the bedroom"
  trigger:
    - platform: event
      event_type: deconz_event
      event_data:
        id: smart_switch_1
        event: 1004
    - platform: event
      event_type: deconz_event
      event_data:
        id: dimmer_switch_bedroom
        event: 1002
  action:
    - service: input_select.select_next
      entity_id: input_select.last_script_bedroom
    - service: script.turn_on
      data_template:
        entity_id: "{{ states('input_select.last_script_bedroom') }}"

- alias: "Light: next colors in the living room"
  trigger:
    - platform: event
      event_type: deconz_event
      event_data:
        id: smart_switch_4
        event: 1004
    - platform: event
      event_type: deconz_event
      event_data:
        id: dimmer_switch_living_room
        event: 1002
  action:
    service: script.next_colors
    data:
      input_select: input_select.last_script_living_room

- alias: "Light: toggle max/min brightness in the bedroom"
  trigger:
    - platform: event
      event_type: deconz_event
      event_data:
        id: smart_switch_1
        event: 1002
    - platform: event
      event_type: deconz_event
      event_data:
        id: dimmer_switch_bedroom
        event: 4002
  action:
    service: script.increase_brightness
    data:
      group: group.bedroom_lights

- alias: "Light: toggle max/min brightness in the living room"
  trigger:
    - platform: event
      event_type: deconz_event
      event_data:
        id: smart_switch_4
        event: 1002
    - platform: event
      event_type: deconz_event
      event_data:
        id: dimmer_switch_living_room
        event: 4002
  action:
    service: script.increase_brightness
    data:
      group: group.living_room_lights

- alias: "Light: turn on kitchen ceiling"
  trigger:
    platform: state
    entity_id: binary_sensor.activity_in_kitchen
  action:
    service_template: light.turn_{{ trigger.to_state.state }}
    entity_id: light.ceiling_kitchen

- alias: "Light: turn on kitchen counter if sleep mode is off"
  trigger:
    platform: state
    entity_id: binary_sensor.activity_in_kitchen
    to: "on"
  condition:
    condition: state
    entity_id: input_boolean.sleep_mode
    state: "off"
  action:
    service: switch.turn_on
    entity_id: switch.kitchen_counter

- alias: "Light: turn off kitchen counter"
  trigger:
    platform: state
    entity_id: binary_sensor.activity_in_kitchen
    to: "off"
  action:
    service: switch.turn_off
    entity_id: switch.kitchen_counter

- alias: "Light: turn on bathroom"
  trigger:
    platform: state
    entity_id: binary_sensor.activity_in_bathroom
  action:
    service_template: light.turn_{{ trigger.to_state.state }}
    entity_id: light.ceiling_bathroom

- alias: "Light: turn on toilet"
  trigger:
    platform: state
    entity_id: binary_sensor.activity_in_toilet
  action:
    service_template: light.turn_{{ trigger.to_state.state }}
    entity_id: light.toilet

# XXX: do not have these sensors yet
# - alias: "Light: automatically turn on the bedroom"
#   initial_state: "on"
#   trigger:
#     platform: state
#     entity_id: binary_sensor.activity_in_bedroom
#     to: "on"
#   condition:
#     - condition: state
#       entity_id: group.bedroom_lights
#       state: "off"
#     - condition: state
#       entity_id: input_boolean.sleep_mode
#       state: "off"
#   action:
#     - service: light.turn_on
#       entity_id: group.bedroom_lights
#       data_template:
#         brightness: 255
#         xy_color: >
#           {{ state_attr("sensor.circadian_values", "xy_color")|list	}}
#     - service: input_boolean.turn_on
#       entity_id: input_boolean.bedroom_lights_auto_on

# - alias: "Light: automatically turn off the bedroom"
#   initial_state: "on"
#   trigger:
#     - platform: state
#       entity_id: binary_sensor.activity_in_bedroom
#       to: "off"
#   condition:
#     - condition: state
#       entity_id: input_boolean.bedroom_lights_auto_on
#       state: "on"
#     - condition: state
#       entity_id: group.bedroom_lights
#       state: "on"
#   action:
#     - service: light.turn_off
#       entity_id: group.bedroom_lights
#       data:
#         transition: 10

# - alias: "Light: turn off bedroom lights auto switch"
#   initial_state: "on"
#   trigger:
#     - platform: state
#       entity_id: group.bedroom_lights
#       to: "off"
#     - platform: event
#       event_type: deconz_event
#       event_data:
#         id: dimmer_switch_bedroom
#     - platform: event
#       event_type: deconz_event
#       event_data:
#         id: smart_switch_1
#   condition:
#     condition: state
#     entity_id: input_boolean.bedroom_lights_auto_on
#     state: "on"
#   action:
#     service: input_boolean.turn_off
#     entity_id: input_boolean.bedroom_lights_auto_on

# XXX: do not have the lights yet!
# - alias: "Light: turn on hall"
#   trigger:
#     - platform: state
#       entity_id: binary_sensor.activity_in_hall
#     - platform: state
#       entity_id: group.persons
#       from: not_home
#       to: home
#     - platform: state
#       entity_id: binary_sensor.openclose_front_door
#       from: "off"
#       to: "on"
#   condition:
#     condition: sun
#     after: sunset
#     after_offset: "-0:30:00"
#   action:
#     service: light.turn_on
#     entity_id:
#       - group.stairs_lights  # XXX: install these lights
#       - group.hall_lights

- alias: "Light: change hue of living room lights with cube"
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: mi_magic_cube
  condition:
    condition: state
    entity_id: input_select.cube_mode
    state: "Hue"
  action:
    service: light.turn_on
    entity_id: group.living_room_lights
    data_template:
      hs_color:
        - >
           {% set hue, sat = state_attr('light.sphere_1', 'hs_color') %}
           {% set delta = trigger.event.data.event / 450 %}
           {% set new_hue = [([0, (hue + delta)]|max), 360]|min %}
           {{ new_hue|round(3) }}
        - >
           {{ state_attr('light.sphere_1', 'hs_color')[1] }}

- alias: "Light: change brightness of living room lights with cube"
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: mi_magic_cube
  condition:
    condition: state
    entity_id: input_select.cube_mode
    state: "Brightness"
  action:
    service: light.turn_on
    entity_id: group.living_room_lights
    data_template:
      brightness: >
        {% set brightness = state_attr('light.sphere_1', 'brightness') %}
        {% set delta = trigger.event.data.event / 450 %}
        {% set new_brightness = [([0, (brightness + delta)]|max), 255]|min %}
        {{ new_brightness|int }}
