---
- alias: "Light: update switch state"  # https://github.com/home-assistant/home-assistant/issues/21768#issuecomment-470959458
  initial_state: "on"
  trigger:
    platform: time_pattern
    seconds: "/5"
  action:
    service: homeassistant.update_entity
    entity_id: switch.desk_lamp

- alias: "Light: copy light"
  trigger:  # two triggers, to avoid triggering on "unavailable"
    - platform: state
      entity_id: sensor.desk_lamp_current
      from: "on"
      to: "off"
    - platform: state
      entity_id: sensor.desk_lamp_current
      from: "off"
      to: "on"
  action:
    service_template: switch.turn_{{ trigger.to_state.state }}
    entity_id: switch.light2

- alias: "Light: turn off when leaving"
  trigger:
    platform: state
    entity_id: group.persons
    from: not_home
    to: home
    for: "00:15:00"
  action:
    - service: light.turn_off
      data:
        entity_id: light.ceiling_bedroom
    - service: switch.turn_off
      data:
        entity_id: switch.desk_lamp

- alias: "Light: turn on when coming home"
  trigger:
    - platform: state
      entity_id: group.persons
      from: not_home
      to: home
    - platform: state
      entity_id: binary_sensor.openclose_1  # XXX: didn't attach this yet!
      from: "off"
      to: "on"
  condition:
    condition: sun
    after: sunset
    after_offset: "-0:30:00"
  action:
    service: light.turn_on
    entity_id: light.ceiling_bedroom

- alias: "Light: turn on night lights with button single click"
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: smart_switch_1
  condition:
    condition: template
    value_template: >
      {{ trigger.event.data.event == 1002 }}
  action:
    service: scene.turn_on
    entity_id: scene.night_lights

- alias: "Light: turn off everything with button double click"
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: smart_switch_1
  condition:
    condition: template
    value_template: >
      {{ trigger.event.data.event == 1004 }}
  action:
    service: scene.turn_on
    entity_id: scene.bed_time
