---
- alias: "Light: update switch state"  # https://github.com/home-assistant/home-assistant/issues/21768#issuecomment-470959458
  initial_state: "on"
  trigger:
    - platform: time_pattern
      seconds: "/5"
  action:
    - service: homeassistant.update_entity
      entity_id: switch.desk_lamp

- alias: "Light: copy light"
  trigger:  # two triggers, such to not trigger on "unavailable"
    - platform: state
      entity_id: sensor.desk_lamp_current
      from: "on"
      to: "off"
    - platform: state
      entity_id: sensor.desk_lamp_current
      from: "off"
      to: "on"
  action:
    - service_template: switch.turn_{{ trigger.to_state.state }}
      entity_id: switch.light2

- alias: "Light: turn off when leaving"
  trigger:
    - platform: state
      entity_id: group.persons
      from: home
      to: not_home
      for: "00:15:00"
  action:
    - service: light.turn_off
      data:
        entity_id: light.ceiling
    - service: switch.turn_off
      data:
        entity_id: switch.desk_lamp
