---
- alias: 'Media player: turn on Opt when TV is on and Spotify is not playing'
  trigger:
    - platform: state
      entity_id: media_player.tv
    - platform: state
      entity_id: media_player.spotify
      to: paused
  condition:
    condition: template
    value_template: >
      {{ (is_state('media_player.tv', 'playing') and not
          is_state_attr('media_player.tv', 'source', 'GALLERY')) and not (
        is_state_attr('media_player.spotify', 'source', 'LS50 Wireless') and
        is_state('media_player.spotify', 'playing')) }}
  action:
    - service: media_player.select_source
      entity_id: media_player.kef
      data:
        source: Opt

- alias: "Media player: update TV state"
  initial_state: "on"
  trigger:
    - platform: time_pattern
      seconds: "/2"
  action:
    - service: homeassistant.update_entity
      entity_id: media_player.tv

- alias: 'Media player: sync TV volume with KEF'
  trigger:
    platform: template
    value_template: >
      {{ state_attr("media_player.tv", "volume_level") }}
  condition:
    condition: template
    value_template: >
      {{ is_state_attr('media_player.kef', 'source', 'Opt') }}
  action:
    - service: media_player.volume_set
      entity_id: media_player.kef
      data_template:
        volume_level: >
          {{ state_attr("media_player.kef", "volume_level") }}

