---
- alias: "Music: start playlist"
  initial_state: "on"
  trigger:
    platform: state
    entity_id: input_boolean.start_the_music
    from: "off"
    to: "on"
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.start_the_music
    - service: script.start_speakers
      data:
        source: Wifi
        volume: 0.25
    - service: script.start_spotify
      data:
        source: LS50 Wireless 00C437
        playlist: 6rPTm9dYftKcFAfwyRqmDZ
        volume: 0.25
