---
#-
#                      _
#  _ __ ___  _   _ ___(_) ___
# | '_ ` _ \| | | / __| |/ __|
# | | | | | | |_| \__ \ | (__
# |_| |_| |_|\__,_|___/_|\___|
#
#
#- from github.com/tmttn/home-assistant-config
- alias: "Music: start playlist"
  initial_state: "on"
  trigger:
    platform: state
    entity_id: input_boolean.start_the_music
    from: "off"
    to: "on"
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.start_the_music
    - service: script.start_spotify_playlist_of_nearest_person
      data:
        source: Google Home
        entity_id: media_player.google_home

- alias: "Music: switch music from iPhone to speakers if coming home"
  trigger:
    platform: state
    entity_id: binary_sensor.openclose_back_door
    from: "off"
    to: "on"
  condition:
    - condition: state
      entity_id: person.tanja
      state: not_home
    - condition: state
      entity_id: input_boolean.guest_mode
      state: "off"
    - "{{ is_state_attr('media_player.spotify', 'source', 'bizzyphone') }}"
    - "{{ is_state('media_player.spotify', 'playing') }}"
    - "{{ as_timestamp(now()) - as_timestamp(states.person.tom.last_changed) < 5 * 60 }}" # recently got home
    - condition: numeric_state
      entity_id: proximity.home
      below: 2
  action:
    - service: spotcast.start
      data:
        entity_id: media_player.google_home
        force_playback: false
