---
#-
#        _       _     _                           _
#  _ __ (_) __ _| |__ | |_     _ __ ___   ___   __| | ___
# | '_ \| |/ _` | '_ \| __|   | '_ ` _ \ / _ \ / _` |/ _ \
# | | | | | (_| | | | | |_    | | | | | | (_) | (_| |  __/
# |_| |_|_|\__, |_| |_|\__|___|_| |_| |_|\___/ \__,_|\___|
#          |___/         |_____|
#
#- from github.com/basnijholt/home-assistant-config

- alias: "Night mode: automatically turn off when alarm turns off or at 7AM"
  trigger:
    - platform: time
      at: "07:00"
    - platform: state
      entity_id: input_boolean.alarm_clock
      from: "on"
      to: "off"
  condition:
    condition: state
    entity_id: input_boolean.alarm_clock
    state: "off"
  action:
    entity_id: input_select.sleep_mode
    service: input_select.select_option
    data:
      option: "off"

- alias: "Night mode: turn off automatic bedroom lights"
  trigger:
    platform: state
    entity_id: input_select.sleep_mode
    from: "off"
  action:
    service: input_boolean.turn_off
    entity_id: input_boolean.automatic_bedroom_lights

- alias: "Night mode: set low temperature when sleep mode turns on"
  trigger:
    platform: state
    entity_id: input_select.sleep_mode
    from: "off"
  action:
    service: script.set_low_temperature

- alias: "Night mode: go from half to total sleeping mode"
  description: >
    When it is half sleeping mode and there is no activity in
    the house for more than an hour go to total sleeping mode.
  trigger:
    platform: state
    entity_id: binary_sensor.activity_outside_bedroom
    to: "off"
    for: "01:00:00"
  condition:
    condition: state
    entity_id: input_select.sleep_mode
    state: half
  action:
    - service: input_select.select_option
      entity_id: input_select.sleep_mode
      data:
        option: "total"
    - service: notify.mobile_app_basnijholt_iphone
      data:
        title: "Night mode"
        message: "Automatically switched from 'half' to 'total' sleeping mode! 💤🛌"
