# No activity anywhere, input_boolean.activity_in_PLACE_HERE should be off
# for 30 minutes (except bedroom).
# TV and lights should be off.
# It's evening or night.
# Both should be home.
# Then if you go out in the middle of the night (e.g., to the bathroom)
# then lights will turn a non-bright red.
# Manually triggering the switch will turn on the normal lights.
# - alias: "Night mode: probably sleeping"
#   trigger:
#     platform: state
#     entity_id: sensor.lovelace
#   action:
#     service: shell_command.convert_lovelace
- alias: "Night mode: automatically turn off if alarm is off"
  trigger:
    - platform: time
      at: "06:00"
    - platform: state
      entity_id: input_boolean.alarm_clock
      from: "on"
      to: "off"
  condition:
    condition: state
    entity_id: input_boolean.alarm_clock
    state: "off"
  action:
    entity_id: input_boolean.sleep_mode
    service: input_boolean.turn_off

- alias: "Night mode: turn off automatic bedroom lights"
  trigger:
    platform: state
    entity_id: input_boolean.sleep_mode
    from: "off"
    to: "on"
  action:
    service: input_boolean.turn_off
    entity_id: input_boolean.automatic_bedroom_lights
