---
#-
#        _       _     _                           _
#  _ __ (_) __ _| |__ | |_     _ __ ___   ___   __| | ___
# | '_ \| |/ _` | '_ \| __|   | '_ ` _ \ / _ \ / _` |/ _ \
# | | | | | (_| | | | | |_    | | | | | | (_) | (_| |  __/
# |_| |_|_|\__, |_| |_|\__|___|_| |_| |_|\___/ \__,_|\___|
#          |___/         |_____|
#
#- from github.com/basnijholt/home-assistant-config

- alias: "Night mode: automatically turn off if alarm is off"
  trigger:
    - platform: time
      at: "06:00"
    - platform: state
      entity_id: input_boolean.alarm_clock
      from: "on"
      to: "off"
  condition:
    condition: state
    entity_id: input_boolean.alarm_clock
    state: "off"
  action:
    entity_id: input_boolean.sleep_mode
    service: input_boolean.turn_off

- alias: "Night mode: turn off automatic bedroom lights"
  trigger:
    platform: state
    entity_id: input_boolean.sleep_mode
    from: "off"
    to: "on"
  action:
    service: input_boolean.turn_off
    entity_id: input_boolean.automatic_bedroom_lights

- alias: "Night mode: set low temperature when sleep mode turns on"
  trigger:
    platform: state
    entity_id: input_boolean.sleep_mode
    from: "off"
    to: "on"
  action:
    service: script.set_low_temperature
