---
#-
#        _             _
#  _ __ | | __ _ _ __ | |_
# | '_ \| |/ _` | '_ \| __|
# | |_) | | (_| | | | | |_
# | .__/|_|\__,_|_| |_|\__|
# |_|
#
#- from github.com/tmttn/home-assistant-config
- alias: "Plant: problem with Calathea Medaillon"
  trigger:
    - platform: state
      entity_id: plant.calathea_medaillon
      to: "problem"
    - platform: time
      at: "20:00"
  condition:
    condition: state
    entity_id: plant.calathea_medaillon
    state: "problem"
  action:
    service: notify.all_iphones
    data:
      title: "Plant in trouble! ⚠️☢️☠️"
      message: >
        You need to give the Calathea Medaillon 🪴 attention and love: {{ state_attr("plant.calathea_medaillon", "problem") }}!

- alias: "Plant: problem with Euphorbia Pulcherrima"
  trigger:
    - platform: state
      entity_id: plant.euphorbia_pulcherrima
      to: "problem"
    - platform: time
      at: "20:00"
  condition:
    condition: state
    entity_id: plant.euphorbia_pulcherrima
    state: "problem"
  action:
    service: notify.all_iphones
    data:
      title: "Plant in trouble! ⚠️☢️☠️"
      message: >
        You need to give the Euphorbia Pulcherrima 🌺 attention and love: {{ state_attr("plant.euphorbia_pulcherrima", "problem") }}!
