---
#-
#        _             _
#  _ __ | | __ _ _ __ | |_
# | '_ \| |/ _` | '_ \| __|
# | |_) | | (_| | | | | |_
# | .__/|_|\__,_|_| |_|\__|
# |_|
#
#- from github.com/tmttn/home-assistant-config
- alias: "Plant: problem with Calathea Medaillon"
  trigger:
    - platform: state
      entity_id: plant.calathea_medaillon
      to: "problem"
    - platform: time
      at: "20:00"
  condition:
    - condition: state
      entity_id: plant.calathea_medaillon
      state: "problem"
    - condition: state
      entity_id: input_boolean.vacation_mode
      state: "off"
    - "{{((now() - as_datetime(states('sensor.uptime'))).seconds)|int > 60}}"
  action:
    service: notify.all_iphones
    data:
      title: "Plant in trouble! ⚠️☢️☠️"
      message: >
        You need to give the Calathea Medaillon 🪴 attention and love: {{ state_attr("plant.calathea_medaillon", "problem") }}!

- alias: "Plant: problem with Peperomia Glabella"
  trigger:
    - platform: state
      entity_id: plant.peperomia_glabella
      to: "problem"
    - platform: time
      at: "20:00"
  condition:
    - condition: state
      entity_id: plant.peperomia_glabella
      state: "problem"
    - condition: state
      entity_id: input_boolean.vacation_mode
      state: "off"
    - "{{((now() - as_datetime(states('sensor.uptime'))).seconds)|int > 60}}"
  action:
    service: notify.all_iphones
    data:
      title: "Plant in trouble! ⚠️☢️☠️"
      message: >
        You need to give the Peperomia Glabella 🌺 attention and love: {{ state_attr("plant.peperomia_glabella", "problem") }}!
