---
#-
#                           _ _
#  ___  ___  ___ _   _ _ __(_) |_ _   _
# / __|/ _ \/ __| | | | '__| | __| | | |
# \__ \  __/ (__| |_| | |  | | |_| |_| |
# |___/\___|\___|\__,_|_|  |_|\__|\__, |
#                                 |___/
#
#- from github.com/basnijholt/home-assistant-config
- alias: "Security: motion detected but we are not home"
  trigger:
    platform: state
    entity_id: binary_sensor.motion_detected
    from: "off"
    to: "on"
  condition:
    - condition: state
      entity_id: group.persons
      state: not_home
    - condition: state
      entity_id: vacuum.xiaomi_vacuum_cleaner
      state: "docked"
  action:
    service: notify.all_iphones
    data:
      message: "Security: motion is detected, but we are not home."
      data:
        push:
          category: sound_alarm

# XXX: Use `wait_for_trigger` the combine the automation below into the one above
- alias: "Security: sound alarm after notification"
  trigger:
    platform: event
    event_type: ios.notification_action_fired
    event_data:
      actionName: SOUND_ALARM
  action:
    service: light.turn_on
    entity_id: all
    data:
      flash: long
      color_name: red

- alias: "Security: door has been open for more than 5 minutes"
  trigger:
    platform: state
    entity_id: binary_sensor.openclose_front_door
    from: "off"
    to: "on"
    for: "00:05:00"
  condition:
    condition: state
    entity_id: input_boolean.guest_mode
    state: "off"
  action:
    service: notify.all_iphones
    data:
      title: "Security"
      message: "The door has been open for more than 5 minutes."

- alias: "Security: no one is home but high power usage"
  trigger:
    - platform: state
      entity_id: binary_sensor.no_one_home
      to: "on"
    - platform: time_pattern
      minutes: "/10"
  condition:
  - condition: state
    entity_id: binary_sensor.no_one_home
    state: "on"
  - condition: numeric_state
    entity_id: sensor.power_consumption
    above: 0.7
  action:
    service: notify.all_iphones
    data:
      title: "Security"
      message: >
        No one is home and we are using a lot of energy
        ({{ states('sensor.power_consumption') }} kW now)! ⚡️
