---
- alias: "Security: motion detected but we are not home"
  trigger:
    platform: state
    entity_id: binary_sensor.motion_detected
    from: "off"
    to: "on"
  condition:
    condition: state
    entity_id: group.persons
    state: not_home
  action:
    service: notify.mobile_app_basnijholt_iphone
    data:
      title: "Security"
      message: "Motion is detected, but we are not home."

- alias: "Security: door has been open for more than 5 minutes"
  trigger:
    platform: state
    entity_id: binary_sensor.openclose_front_door
    from: "off"
    to: "on"
    for: "00:05:00"
  action:
    service: notify.mobile_app_basnijholt_iphone
    data:
      title: "Security"
      message: "The door has been open for more than 5 minutes."

