---
#-
#            _
#  ___  ___ | | __ _ _ __
# / __|/ _ \| |/ _` | '__|
# \__ \ (_) | | (_| | |
# |___/\___/|_|\__,_|_|
#
#
#- from github.com/tmttn/home-assistant-config
- alias: "Solar: grid export too high"
  trigger:
    - platform: numeric_state
      entity_id: sensor.grid_export_last_hour
      above: 0.7
  condition:
    - condition: state
      entity_id: input_boolean.vacation_mode
      state: "off"
  action:
    - service: notify.all_iphones
      data:
        title: "Energy"
        message: "Grid export is above 0.7kWh, please increase self-consumption. ⚡"
    - delay: "00:30:00"
