---
#-
#            _
#  ___  ___ | | __ _ _ __
# / __|/ _ \| |/ _` | '__|
# \__ \ (_) | | (_| | |
# |___/\___/|_|\__,_|_|
#
#
#- from github.com/tmttn/home-assistant-config
- alias: "Solar: grid export too high"
  trigger:
    - platform: numeric_state
      entity_id: sensor.grid_export_last_hour
      above: 0.7
  action:
    - service: notify.all_iphones
      data:
        title: "Energy"
        message: "Grid export is above 1kWh, please increase self-consumption. ⚡"
    - service: automation.turn_off
      entity_id: automation.solar_grid_export_too_high

- alias: "Solar: turn grid export warning automation on again"
  trigger:
    - platform: time_pattern
      minutes: "/30"
  action:
    - service: automation.turn_on
      entity_id: automation.grid_export_too_high
