---
#-
#                _
#  ___ _   _ ___| |_ ___ _ __ ___
# / __| | | / __| __/ _ \ '_ ` _ \
# \__ \ |_| \__ \ ||  __/ | | | | |
# |___/\__, |___/\__\___|_| |_| |_|
#      |___/
#
#- from github.com/basnijholt/home-assistant-config
- alias: "System: warning about high CPU usage"
  trigger:
    platform: numeric_state
    entity_id: sensor.processor_use
    above: 70
    for:
      hours: 4
  action:
    service: notify.mobile_app_basnijholt_iphone
    data:
      title: "System"
      message: "CPU usage has been above 70% for 4 hours! ⚠️🖥"

- alias: "System: warning about high CPU temperature"
  trigger:
    platform: numeric_state
    entity_id: sensor.processor_use # XXX: this isn't using the CPU temperature!
    above: 70
    for:
      hours: 4
  action:
    service: notify.mobile_app_basnijholt_iphone
    data:
      title: "System"
      message: "CPU temperature has been above 70 °C for 4 hours! ⚠️"

- alias: "System: warning about high Xbox temperature"
  trigger:
    platform: numeric_state
    entity_id: sensor.temperature_xbox
    above: 50
  action:
    - service: notify.mobile_app_basnijholt_iphone
      data:
        title: "System"
        message: >
          Temperature in the Xbox cabinet is {{ states("sensor.temperature_xbox") }} °C! ⚠️
    - condition: state
      entity_id: media_player.tv
      state: "on"
    - service: notify.tv
      data:
        message: >
          Temperature in the Xbox cabinet is {{ states("sensor.temperature_xbox") }} °C! ⚠️

- alias: "System: update DNS"
  description: Update the DNS at Gandi to point my domain to my Home Assistant instance.
  trigger:
    platform: time_pattern # XXX: trigger on IP change
    minutes: "/15"
  action:
    service: script.update_dns

- alias: "System: run chores"
  description: Run shell and Python scripts in utils folder.
  trigger:
    platform: time_pattern
    minutes: "/15"
  action:
    service: shell_command.chores
