---
#-
#                _
#  ___ _   _ ___| |_ ___ _ __ ___
# / __| | | / __| __/ _ \ '_ ` _ \
# \__ \ |_| \__ \ ||  __/ | | | | |
# |___/\__, |___/\__\___|_| |_| |_|
#      |___/
#
#- from github.com/tmttn/home-assistant-config
- alias: "System: warning about high CPU usage"
  trigger:
    platform: numeric_state
    entity_id: sensor.processor_use
    above: 70
    for:
      hours: 4
  action:
    service: notify.mobile_app_bizzyphone
    data:
      title: "System"
      message: "CPU usage has been above 70% for 4 hours! âš ï¸ðŸ–¥"

- alias: "System: update DNS"
  description: Update the DNS at Gandi to point my domain to my Home Assistant instance.
  trigger:
    platform: time_pattern # XXX: trigger on IP change
    minutes: "/15"
  action:
    service: script.update_dns

- alias: "System: run chores"
  description: Run shell and Python scripts in utils folder.
  trigger:
    platform: time_pattern
    minutes: "/15"
  action:
    service: shell_command.chores

- alias: "System: battery level low"
  trigger:
    platform: time
    at: "14:30:00"
  variables:
    min_battery_level: 50
    notify_service: notify.mobile_app_bizzyphone
    battery_ids: ""
    current: ""
  action:
    - variables:
        battery_ids: >
          {% set ns = namespace(battery=[]) %}
          {% for s in states.sensor if 'battery_level' in s.entity_id %}
            {% set ns.battery = ns.battery + [s] %}
          {% endfor %}
          {{ ns.battery | map(attribute='entity_id') | list }}
    - alias: Repeat
      repeat:
        count: "{{ battery_ids | length }}"
        sequence:
          - variables:
              current: "{{ battery_ids[repeat.index - 1] }}"
          - condition: template
            value_template: "{{ 'iphone' not in current and 'ipad' not in current }}"
          - condition: template
            value_template: "{{ 0 < (states(current) | float) < (min_battery_level | float ) }}"
          - service: "{{ notify_service }}"
            data:
              title: "System"
              message: "Battery level low of {{ current }}: {{ states(current) }}%! âš ï¸"
