---
#-
#  _                              __  __
# | |_ _   _ _ __ _ __      ___  / _|/ _|
# | __| | | | '__| '_ \    / _ \| |_| |_
# | |_| |_| | |  | | | |  | (_) |  _|  _|
#  \__|\__,_|_|  |_| |_|___\___/|_| |_|
#                     |_____|
#
#- from github.com/basnijholt/home-assistant-config
- alias: "Turn off: turn off the living room"
  trigger:
    - platform: event
      event_type: deconz_event
      event_data:
        id: smart_switch_living_room
        event: 1007
  action:
    - service: media_player.turn_off
      entity_id: media_player.tv
    - service: media_player.turn_off
      entity_id: media_player.kef_ls50
    - service: light.turn_off
      entity_id: light.living_room_lights
      data:
        transition: 30

- alias: "Turn off: turn off the bedroom"
  trigger:
    - platform: event
      event_type: deconz_event
      event_data:
        id: smart_switch_bedroom
        event: 1007
  action:
    - service: light.turn_off
      entity_id: light.bedroom_lights
    - service: light.turn_off
      entity_id: light.living_room_lights
      data:
        transition: 10
    - service: script.going_to_sleep