---
#-
#  _                              __  __
# | |_ _   _ _ __ _ __      ___  / _|/ _|
# | __| | | | '__| '_ \    / _ \| |_| |_
# | |_| |_| | |  | | | |  | (_) |  _|  _|
#  \__|\__,_|_|  |_| |_|___\___/|_| |_|
#                     |_____|
#
#- from github.com/basnijholt/home-assistant-config
- alias: "Turn off: turn off the living room"
  trigger:
    - platform: event
      event_type: deconz_event
      event_data:
        id: smart_switch_living_room
        event: 1007  # Shake button
  action:
    - service: media_player.turn_off
      entity_id: media_player.tv
    - service: media_player.turn_off
      entity_id: media_player.kef_ls50
    - service: light.turn_off
      entity_id: light.living_room_lights
      data:
        transition: 30

- alias: "Turn off: turn off the bedroom"
  trigger:
    - platform: event
      event_type: deconz_event
      event_data:
        id: smart_switch_bedroom
        event: 1007  # Shake button
  action:
    - service: light.turn_off
      entity_id: light.bedroom_lights
    - service: light.turn_off
      entity_id: light.living_room_lights
      data:
        transition: 10
    - service_template: >
        {% set h, m = states("sensor.ten_minutes_before_alarm").split(":") %}
        {% set t_diff = as_timestamp(now()) - as_timestamp(now().replace(hour=h|int, minute=m|int)) %}
        {% set is_near_alarm = (t_diff|abs) < 1800 %}
        {% set is_morning = now().replace(hour=6, minute=0) < now() < now().replace(hour=12, minute=0) %}
        {% if is_near_alarm or is_morning %}
          script.turn_off_everything_non_automatic
        {% else %}
          script.going_to_sleep
        {% endif %}

