---
#-
#        _   _ _ _ _   _
#  _   _| |_(_) (_) |_(_) ___  ___
# | | | | __| | | | __| |/ _ \/ __|
# | |_| | |_| | | | |_| |  __/\__ \
#  \__,_|\__|_|_|_|\__|_|\___||___/
#
#
#- from github.com/basnijholt/home-assistant-config

- alias: "Utilities: washing machine has started"
  trigger:
    platform: state
    entity_id: binary_sensor.washing_machine
    from: "off"
    to: "on"
  action:
    service: input_datetime.set_datetime
    entity_id: input_datetime.washing_machine_started
    data_template:
      datetime: "{{ now().strftime('%Y-%m-%d %H:%M:%S') }}"

- alias: "Utilities: washing machine is done"
  trigger:
    platform: state
    entity_id: binary_sensor.washing_machine
    from: "on"
    to: "off"
  action:
    - service: input_datetime.set_datetime
      entity_id: input_datetime.washing_machine_done
      data_template:
        datetime: "{{ now().strftime('%Y-%m-%d %H:%M:%S') }}"
    - service_template: >
        {{ states("sensos.nearest_iphone_notify") }}
      data:
        title: "Utilities"
        message: "Washing machine is done 👚👕"

- alias: "Utilities: dishwasher is done"
  trigger:
    platform: state
    entity_id: binary_sensor.dishwasher
    from: "on"
    to: "off"
  action:
    - service: input_datetime.set_datetime
      entity_id: input_datetime.dishwasher_done
      data_template:
        datetime: "{{ now().strftime('%Y-%m-%d %H:%M:%S') }}"
    - service_template: >
        {{ states("sensos.nearest_iphone_notify") }}
      data:
        title: "Utilities"
        message: "Dishwasher is done 🍽🍳"

- alias: "Utilities: dishwasher has started"
  trigger:
    platform: state
    entity_id: binary_sensor.dishwasher
    from: "off"
    to: "on"
  action:
    service: input_datetime.set_datetime
    entity_id: input_datetime.dishwasher_started
    data_template:
      datetime: "{{ now().strftime('%Y-%m-%d %H:%M:%S') }}"
