---
#-
#        _   _ _ _ _   _
#  _   _| |_(_) (_) |_(_) ___  ___
# | | | | __| | | | __| |/ _ \/ __|
# | |_| | |_| | | | |_| |  __/\__ \
#  \__,_|\__|_|_|_|\__|_|\___||___/
#
#
#- from github.com/tmttn/home-assistant-config

- alias: "Utilities: washing machine, dishwasher,tumble dryer or espresso machine started or finished"
  trigger:
    - platform: state
      entity_id: binary_sensor.dishwasher
    - platform: state
      entity_id: binary_sensor.washing_machine
    - platform: state
      entity_id: binary_sensor.tumble_dryer
    - platform: state
      entity_id: binary_sensor.espresso_machine
  variables:
    from_state: "{{ trigger.from_state.state }}"
    to_state: "{{ trigger.to_state.state }}"
    name: "{{ trigger.entity_id.split('.', 1)[1] }}"
  condition: "{{ (to_state == 'on' and from_state == 'off') or (to_state == 'off' and from_state == 'on') }}"
  action:
    service: input_datetime.set_datetime
    data:
      entity_id: "input_datetime.{{ name }}_{{ to_state }}"
      timestamp: "{{ now().timestamp() }}"

- alias: "Utilities: washing machine notification"
  trigger:
    platform: state
    entity_id: miele.washing_machine
    from: "Off"
    to: "In use"
  action:
    service: script.utility_notification
    data:
      name: "washing_machine"
      emojis: "👚👕"

- alias: "Utilities: dishwasher notification"
  trigger:
    platform: state
    entity_id: binary_sensor.dishwasher
    from: "off"
    to: "on"
  action:
    service: script.utility_notification
    data:
      name: "dishwasher"
      emojis: "🍽🍳"

- alias: "Utilities: tumble dryer notification"
  trigger:
    platform: state
    entity_id: binary_sensor.tumble_dryer
    from: "off"
    to: "on"
  action:
    service: script.utility_notification
    data:
      name: "tumble dryer"
      emojis: "🧺💦"

- alias: "Utilities: espresso machine notification"
  trigger:
    platform: state
    entity_id: binary_sensor.tumble_dryer
    from: "off"
    to: "on"
  action:
    service: script.utility_notification
    data:
      name: "espresso machine"
      emojis: "☕️🥤"
