---
- alias: "Vacation mode: toggle on or off"
  initial_state: "on"
  trigger:
    platform: state
    entity_id: input_boolean.vacation_mode
  action:
    service_template: >
      automation.turn_{{ "off" if trigger.to_state.state == "on" else "on"}}
    entity_id: group.vacation_mode

- alias: "Vacation mode: auto turn on"
  initial_state: "on"
  trigger:
    platform: state
    entity_id: group.persons
    from: home
    to: not_home
    for: "24:00:00"
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.vacation_mode
    - service: notify.mobile_app_basnijholt_iphone
      data:
        title: "Vacation mode"
        message: "No one at home for 24 hours, switching on vacation mode."

- alias: "Vacation mode: auto turn off"
  initial_state: "on"
  trigger:
    platform: state
    entity_id: group.persons
    from: not_home
    to: home
  condition:
    condition: state
    entity_id: input_boolean.vacation_mode
    state: "on"
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.vacation_mode
    - service: notify.mobile_app_basnijholt_iphone
      data:
        title: "Vacation mode"
        message: "Welcome back! Switching off the vacation mode."
