---
#-
#
# __   ____ _  ___ _   _ _   _ _ __ ___
# \ \ / / _` |/ __| | | | | | | '_ ` _ \
#  \ V / (_| | (__| |_| | |_| | | | | | |
#   \_/ \__,_|\___|\__,_|\__,_|_| |_| |_|
#
#
#- from github.com/tmttn/home-assistant-config
- alias: "Vacuum: started cleaning"
  trigger:
    platform: state
    entity_id: vacuum.robot_vacuum
    from: docked
    to: cleaning
  action:
    service: notify.all_iphones
    data:
      title: "Robot"
      message: "Robot started to clean!"

- alias: "Vacuum: stopped cleaning"
  trigger:
    platform: state
    entity_id: vacuum.robot_vacuum
    from: returning
    to: docked
  action:
    - service: notify.all_iphones
      data:
        title: "Robot"
        message: "Cleanup successful after {{ (states.sensor.vacuum_last_clean_duration|int / 60)|round }} minutes."
    - service: input_boolean.turn_on
      entity_id: input_boolean.cleaned_today
    - service: counter.increment
      entity_id: counter.vacuum_bin_counter

- alias: "Vacuum: reminder notification"
  trigger:
    platform: time
    at: "07:00"
  condition:
    condition: state
    entity_id: binary_sensor.vacuum_day
    state: "on"
  action:
    service: notify.all_iphones
    data:
      title: "Robot"
      message: "Vacuum will go today, make sure to leave the doors open and leave nothing on the floor!"

- alias: "Vacuum: cleanup if nobody is home"
  trigger:
    - platform: time
      at: "08:30"
    - platform: state
      entity_id: group.persons
      from: home
      to: not_home
    - platform: state
      entity_id: binary_sensor.openclose_guest_bedroom
      from: "off"
      to: "on"
  condition:
    - condition: time
      after: "07:00:00"
      before: "22:00:00"
    - condition: state
      entity_id: binary_sensor.vacuum_day
      state: "on"
    - condition: state
      entity_id: group.persons
      state: not_home
    - condition: state
      entity_id: input_boolean.cleaned_today
      state: "off"
    - condition: state
      entity_id: input_boolean.guest_mode
      state: "off"
    - condition: state
      entity_id: input_boolean.vacation_mode
      state: "off"
  action:
    service: vacuum.start
    entity_id: vacuum.robot_vacuum

- alias: "Vacuum: reset cleaned today"
  initial_state: true
  trigger:
    platform: time
    at: "00:00:00"
  action:
    service: input_boolean.turn_off
    entity_id: input_boolean.cleaned_today

- alias: "Vacuum: reset to standard mode"
  trigger:
    platform: state
    entity_id: vacuum.living_room
    to: docked
  action:
    service: vacuum.set_fan_speed
    entity_id: vacuum.robot_vacuum
    data:
      fan_speed: Standard

- alias: "Vacuum: bin is full"
  trigger:
    - platform: numeric_state
      above: "3"
      entity_id: counter.vacuum_bin_counter
  action:
    - service: notify.all_iphones
      data:
        title: "Robot"
        message: "Vacuum dust bin is full, please empty it!"
    - service: tts.google_translate_say
      data:
        entity_id: media_player.google_home
        language: nl
        message: Het stofbakje van Brenda is vol. Maak het stofbakje leeg alstublieft.

- alias: "Vacuum: water reservoir empty"
  trigger:
    - platform: state
      entity_id: binary_sensor.vacuum_water_shortage
      to: "on"
  action:
    - service: vacuum.pause
    - service: notify.all_iphones
      data:
        title: "Robot"
        message: "Water reservoir is empty, please fill it! 🚰"
        data:
          actions:
            - action: RESUME_CLEANING
              title: Resume cleaning
              activationMode: background
              authenticationRequired: true
              destructive: true
    - service: tts.google_translate_say
      data:
        entity_id: media_player.google_home
        language: nl
        message: Het water reservoir van Brenda is leeg. Vul het water reservoir alstublieft.
    - wait_for_trigger:
        platform: event
        event_type: mobile_app_notification_action
        event_data:
          action: RESUME_CLEANING
      timeout: "00:05:00"
      continue_on_timeout: false
    - service: vacuum.start

- alias: "Vacuum: sensors need cleaning"
  trigger:
    platform: state
    entity_id: vacuum.robot_vacuum
    from: returning
    to: docked
  condition:
    - condition: numeric_state
      entity_id: sensor.vacuum_sensor_dirty_left
      below: 0
  action:
    - service: notify.all_iphones
      data:
        title: "Robot"
        message: "Sensors need cleaning!"

- alias: "Vacuum: main brush needs replacing"
  trigger:
    platform: state
    entity_id: vacuum.robot_vacuum
    from: returning
    to: docked
  condition:
    - condition: numeric_state
      entity_id: sensor.vacuum_main_brush_left
      below: 0
  action:
    - service: notify.all_iphones
      data:
        title: "Robot"
        message: "Main brush needs replacing!"

- alias: "Vacuum: side brush needs replacing"
  trigger:
    platform: state
    entity_id: vacuum.robot_vacuum
    from: returning
    to: docked
  condition:
    - condition: numeric_state
      entity_id: sensor.vacuum_side_brush_left
      below: 0
  action:
    - service: notify.all_iphones
      data:
        title: "Robot"
        message: "Side brush needs replacing!"

- alias: "Vacuum: air filter needs replacing"
  trigger:
    platform: state
    entity_id: vacuum.robot_vacuum
    from: returning
    to: docked
  condition:
    - condition: numeric_state
      entity_id: sensor.vacuum_filter_left
      below: 0
  action:
    - service: notify.all_iphones
      data:
        title: "Robot"
        message: "Air filter needs replacing!"
