---
- alias: "Work: go home notification"
  trigger:
    platform: state
    entity_id: binary_sensor.worked_enough_today
    from: "off"
    to: "on"
  condition:
    condition: state
    entity_id: binary_sensor.workday_sensor
    state: "on"
  action:
    service: notify.mobile_app_basnijholt_iphone
    data:
      title: "Work"
      message: "You have worked 8 hours today, very good! Go home 🎉"

- alias: "Work: update sensor.timestamp_start_of_today"
  trigger:
    platform: time
    at: "00:01"
  action:
    service: homeassistant.update_entity
    entity_id: sensor.timestamp_start_of_today
