---
- alias: Update power  # https://github.com/home-assistant/home-assistant/issues/21768#issuecomment-470959458
  id: update_power
  initial_state: "on"
  trigger:
    - platform: time_pattern
      seconds: "/5"
  action:
    - service: homeassistant.update_entity
      entity_id: switch.desk_lamp

- alias: Start the music
  id: start_the_music
  initial_state: "on"
  trigger:
    - platform: state
      entity_id: input_boolean.start_the_music
      from: "off"
      to: "on"
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.start_the_music
    - service: script.start_speakers
      data:
        source: "Wifi"
        volume: "0.35"
    - service: script.start_spotify
      data:
        source: "KEF LS50 Wireless"
        playlist: "6rPTm9dYftKcFAfwyRqmDZ"
        volume: "0.35"

- alias: Turn off speakers when away
  id: turn_off_speakers_when_away
  trigger:
    - platform: state
      entity_id: group.persons
      from: "home"
      to: "not_home"
      for: "00:15:00"
  action:
    - service: switch.turn_off
      entity_id: switch.kef_speakers
