---
- alias: Copy light
  id: copy_light
  trigger:
    - platform: state
      entity_id: sensor.desk_lamp_current
  action:
    - service_template: switch.turn_{{ trigger.to_state.state }}
      entity_id: switch.light2

- alias: Turn off lights when leaving
  id: 'turn_off_lights_when_leaving'
  trigger:
    - platform: state
      entity_id: group.persons
      from: home
      to: not_home
      for: "00:15:00"
  action:
    - service: light.turn_off
      data:
        entity_id: light.ceiling
    - service: switch.turn_off
      data:
        entity_id: switch.desk_lamp
