---
#-
#  _     _
# | |__ (_)_ __   __ _ _ __ _   _     ___  ___ _ __  ___  ___  _ __ ___
# | '_ \| | '_ \ / _` | '__| | | |   / __|/ _ \ '_ \/ __|/ _ \| '__/ __|
# | |_) | | | | | (_| | |  | |_| |   \__ \  __/ | | \__ \ (_) | |  \__ \
# |_.__/|_|_| |_|\__,_|_|   \__, |___|___/\___|_| |_|___/\___/|_|  |___/
#                           |___/_____|
#
#- from github.com/tmttn/home-assistant-config

- platform: template
  sensors:
    someone_showering:
      friendly_name: Someone is showering or taking a bath
      value_template: >
        {% set humidity = states("sensor.humidity_bathroom") | float(0) %}
        {% set treshold = 1.05 * state_attr("sensor.humidity_bathroom_stats", "median") | float(0) %}
        {% set derivative = states("sensor.humidity_bathroom_derivative") | float(0) %}
        {{ humidity > treshold and derivative > 0.25 }}

    someone_showering_storage:
      friendly_name: Someone is showering in the storage
      value_template: >
        {% set humidity = states("sensor.humidity_storage") | float(0) %}
        {% set treshold = 1.05 * state_attr("sensor.humidity_storage_stats", "median") | float(0) %}
        {% set derivative = states("sensor.humidity_storage_derivative") | float(0) %}
        {{ humidity > treshold and derivative > 0.25 }}

    motion_detected:
      friendly_name: Any motion detected
      value_template: >
        {{ is_state("binary_sensor.activity_in_kitchen", "on")
            or is_state("binary_sensor.activity_in_living_room", "on")
            or is_state("binary_sensor.activity_in_hall", "on")
            or is_state("binary_sensor.activity_in_toilet", "on")
            or is_state("binary_sensor.activity_in_bathroom", "on")
            or is_state("binary_sensor.activity_in_bedroom", "on")
            or is_state("binary_sensor.activity_in_guest_bedroom", "on") }}

    motion_detected_in_last_hour:
      friendly_name: Any motion detected in last hour
      value_template: >
        {{ is_state("binary_sensor.motion_detected", "on") }}
      delay_off: "01:00:00"

    someone_in_the_house_in_last_hour:
      friendly_name: Someone in the house in the last hour
      value_template: >
        {{ is_state("binary_sensor.motion_detected_in_last_hour", "on")
            or is_state("group.persons", "home") }}

    activity_in_bathroom:
      friendly_name: Activity in the bathroom
      value_template: >
        {{ is_state("binary_sensor.motion_sensor_bathroom", "on")
            or is_state("binary_sensor.someone_showering", "on") }}
      delay_off: "00:03:00"

    activity_in_living_room:
      friendly_name: Activity in the living room
      value_template: >
        {{ is_state("binary_sensor.motion_sensor_living_room", "on")
            or is_state("media_player.tv", "on")
            or is_state("binary_sensor.openclose_back_door", "on")
            or is_state("binary_sensor.openclose_living_room_door", "on") }}
      delay_off: "00:20:00"

    activity_in_toilet:
      friendly_name: Activity at the toilet
      value_template: >
        {{ is_state("binary_sensor.motion_sensor_toilet", "on") }}
      delay_off: "00:05:00"

    activity_in_kitchen:
      friendly_name: Activity in the kitchen
      value_template: >
        {{ is_state("binary_sensor.motion_sensor_kitchen", "on")
            or is_state("binary_sensor.openclose_storage_door", "on") }}
      delay_off: "00:05:00"

    activity_in_storage:
      friendly_name: Activity in the storage
      value_template: >
        {{ is_state("binary_sensor.openclose_storage_door", "on")
            or is_state("binary_sensor.someone_showering_storage", "on")}}
      delay_off: "00:05:00"

    activity_in_hall:
      friendly_name: Activity in the hall
      value_template: >
        {{ is_state("binary_sensor.motion_sensor_lower_hall", "on")
            or is_state("binary_sensor.motion_sensor_lower_hall_2", "on")
            or is_state("binary_sensor.motion_sensor_upper_hall", "on")
            or is_state("binary_sensor.openclose_front_door", "on")
            or is_state("binary_sensor.openclose_living_room_door", "on") }}
      delay_off: "00:01:00"

    activity_in_bedroom:
      friendly_name: Activity in the bedroom
      value_template: >
        {{ is_state("binary_sensor.motion_sensor_bedroom_door", "on")
            or is_state("binary_sensor.motion_sensor_bedroom_kabinet", "on")
            or is_state("binary_sensor.motion_sensor_bedroom_desk", "on")
            or is_state("binary_sensor.vibration", "on") }}
      delay_off: "00:01:00"

    activity_in_guest_bedroom:
      friendly_name: Activity in the guest bedroom
      value_template: >
        {{ is_state("binary_sensor.motion_sensor_guest_bedroom", "on") }}
      delay_off: "00:01:00"

    activity_outside_bedroom:
      friendly_name: Activity outside the bedroom
      value_template: >
        {{ is_state("binary_sensor.activity_in_hall", "on")
            or is_state("binary_sensor.activity_in_living_room", "on")
            or is_state("binary_sensor.activity_in_toilet", "on")
            or is_state("binary_sensor.activity_in_kitchen", "on")
            or is_state("binary_sensor.activity_in_bathroom", "on")
            or is_state("binary_sensor.activity_in_storage", "on") }}
      delay_off: "00:01:00"

    washing_machine:
      friendly_name: Washing machine
      value_template: >
        {{ is_state("miele.washing_machine", "In use") }}
      delay_off: "00:01:00"
      icon_template: >
        {% if is_state("binary_sensor.washing_machine", "on") %}
          mdi:washing-machine
        {% else %}
          mdi:washing-machine-off
        {% endif %}

    dishwasher:
      friendly_name: Dishwasher
      value_template: >
        {{ states("sensor.dishwasher_current_consumption") | float(0) > 3 }}
      delay_off: "00:03:00"
      icon_template: >
        {% if is_state("binary_sensor.dishwasher", "on") %}
          mdi:dishwasher
        {% else %}
          mdi:dishwasher-off
        {% endif %}

    espresso_machine:
      friendly_name: Espresso machine
      value_template: >
        {{ states("sensor.espresso_machine_current_consumption") | float(0) > 3 }}
      delay_off: "00:03:00"
      icon_template: >
        {% if is_state("binary_sensor.espresso_machine", "on") %}
          mdi:coffee-maker
        {% else %}
          mdi:coffee-maker
        {% endif %}

    tumble_dryer:
      friendly_name: Tumble dryer
      value_template: >
        {{ states("sensor.tumble_dryer_current_consumption") | float(0) > 350 }}
      delay_off: "00:10:00"
      icon_template: >
        {% if is_state("binary_sensor.tumble_dryer", "on") %}
          mdi:tumble-dryer
        {% else %}
          mdi:tumble-dryer-off
        {% endif %}

    worked_enough_today:
      friendly_name: Worked enough today
      value_template: >
        {{ states("sensor.time_at_work_today") | float(0) > 8 }}
      icon_template: mdi:briefcase

    any_light_on:
      friendly_name: Any light is on
      value_template: >
        {% set automatic_lights_on = is_state("light.automatic_lights", "on") %}
        {% set bedroom_lights_on = is_state("light.bedroom_lights", "on") %}
        {% set living_room_lights_on = is_state("light.living_room_lights", "on") %}
        {% set bathroom_lights_on = is_state("light.bathroom_lights", "on") %}
        {% set guest_bedroom_lights_on = is_state("light.guest_bedroom_lights", "on") %}
        {{ automatic_lights_on or bedroom_lights_on or living_room_lights_on or bathroom_lights_on or guest_bedroom_lights_on }}

    anything_on:
      friendly_name: Anything is on
      value_template: >
        {% set light_on = is_state("binary_sensor.any_light_on", "on") %}
        {% set tv_on = is_state("media_player.tv", "on") %}
        {{ light_on or tv_on }}

    vacuum_day:
      # XXX: was '("Mon", "Wed", "Sun")'  pre-corona because now we're mostly at home
      friendly_name: Vacuum day today
      value_template: >
        {{ as_timestamp(now()) | timestamp_custom("%a") in ("Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun") }}

    no_one_home:
      friendly_name: No one is home
      value_template: >
        {{ not is_state("person.tom", "home")
            and not is_state("person.tanja", "home") }}

- platform: workday
  country: BE

- platform: trend
  sensors:
    humidity_bathroom_trend:
      entity_id: sensor.humidity_bathroom
      sample_duration: 300
      max_samples: 3

    humidity_storage_trend:
      entity_id: sensor.humidity_bathroom_storage
      sample_duration: 300
      max_samples: 3
