---
- platform: template
  sensors:
    someone_showering:
      friendly_name: Someone is showering
      value_template: >
        {{ states("sensor.humidity_bathroom") | float(0) > 90 }}

    motion_detected:
      friendly_name: Any motion detected
      value_template: >
        {{ states("binary_sensor.activity_in_kitchen") == "on"
           or states("binary_sensor.activity_in_hall") == "on"
           or states("binary_sensor.activity_in_toilet") == "on"
           or states("binary_sensor.activity_in_bathroom") == "on"
           or states("binary_sensor.activity_in_bedroom") == "on" }}

    motion_detected_in_last_hour:
      friendly_name: Any motion detected in last hour
      value_template: >
        {{ states("binary_sensor.motion_detected") == "on" }}
      delay_off: "01:00:00"

    someone_in_the_house_in_last_hour:
      friendly_name: Someone in the house in the last hour
      value_template: >
        {{ states("binary_sensor.motion_detected_in_last_hour") == "on"
           or states("group.persons") == "home" }}

    activity_in_bathroom:
      friendly_name: Activity in the bathroom
      value_template: >
        {{ states("binary_sensor.motion_sensor_bathroom") == "on"
           or states("binary_sensor.someone_showering") == "on" }}
      delay_off: "00:03:00"

    activity_in_toilet:
      friendly_name: Activity at the toilet
      value_template: >
        {{ states("binary_sensor.motion_sensor_toilet") == "on" }}
      delay_off: "00:01:00"

    activity_in_kitchen:
      friendly_name: Activity in the kitchen
      value_template: >
        {{ states("binary_sensor.motion_sensor_kitchen") == "on" }}
      delay_off: "00:01:00"

    activity_in_hall:
      friendly_name: Activity in the hall
      value_template: >
        {{ states("binary_sensor.motion_sensor_hall") == "on"
           or states("binary_sensor.openclose_front_door") == "on" }}
      delay_off: "00:01:00"

    activity_in_bedroom:
      friendly_name: Activity in the bedroom
      value_template: >
        {{ states("binary_sensor.motion_sensor_bedroom_1") == "on"
           or states("binary_sensor.motion_sensor_bedroom_2") == "on" }}
      delay_off: "00:01:00"

    washing_machine:
      friendly_name: Washing machine
      value_template: >
        {{ states("sensor.washing_machine_watts") | float(0) > 3 }}
      delay_off: "00:04:00"
      icon_template: >
        {% if states("binary_sensor.washing_machine") == "on" %}
          mdi:washing-machine
        {% else %}
          mdi:washing-machine-off
        {% endif %}

    dishwasher:
      friendly_name: Dishwasher
      value_template: >
        {{ states("sensor.dishwasher_watts") | float(0) > 3 }}
      delay_off: "00:03:00"
      icon_template: >
        {% if states("binary_sensor.dishwasher") == "on" %}
          mdi:dishwasher
        {% else %}
          mdi:dishwasher-off
        {% endif %}

    worked_enough_today:
      friendly_name: Worked enough today
      value_template: >
        {{ states("sensor.time_at_work_today") | float(0) > 8 }}
      icon_template: mdi:work

    any_light_on:
      friendly_name: Any light is on
      value_template: >
        {% set automatic_lights_on = is_state("light.automatic_lights", "on") %}
        {% set bedroom_lights_on = is_state("light.bedroom_lights", "on") %}
        {% set living_room_lights_on = is_state("light.living_room_lights", "on") %}
        {{ automatic_lights_on or bedroom_lights_on or living_room_lights_on }}

    anything_on:
      friendly_name: Anything is on
      value_template: >
        {% set light_on = is_state("binary_sensor.any_light_on", "on") %}
        {% set tv_on = is_state("media_player.tv", "on") %}
        {% set kef_on = is_state("media_player.kef_ls50", "on") %}
        {% set kef_lsx_on = is_state("media_player.kef_lsx", "on") %}
        {{ light_on or tv_on or kef_on or kef_lsx_on }}

    vacuum_day:
      friendly_name: Vacuum vacuum_day
      value_template: >
        {{ as_timestamp(now()) | timestamp_custom("%a") in ("Mon", "Wed", "Fri", "Sun") }}

- platform: workday
  country: NL
