---
#-
#
#   ___ __ _ _ __ ___   ___ _ __ __ _
#  / __/ _` | '_ ` _ \ / _ \ '__/ _` |
# | (_| (_| | | | | | |  __/ | | (_| |
#  \___\__,_|_| |_| |_|\___|_|  \__,_|
#
#
#- from github.com/tmttn/home-assistant-config

- platform: xiaomi_cloud_map_extractor
  host: 192.168.87.42
  token: !secret xiaomi_cloud_token
  username: !secret xiaomi_cloud_username
  password: !secret xiaomi_cloud_password
  draw: ["all"]
  map_transformation:
    trim:
      left: 20
      top: 15
      right: 25
      bottom: 25
  attributes:
    - calibration_points

- platform: generic
  name: Front Door Video
  still_image_url: https://zwart-paard.local:8123{{ states.camera.front_door_snapshot.attributes.entity_picture }}
  stream_source: rtsp://03cabcc9-ring-mqtt:8554/74e182314675_live

- platform: generic
  name: Porch Video
  still_image_url: https://zwart-paard.local:8123{{ states.camera.porch_snapshot.attributes.entity_picture }}
  stream_source: rtsp://03cabcc9-ring-mqtt:8554/184516a7ad19_live

- platform: generic
  name: Front Garden Video
  still_image_url: https://zwart-paard.local:8123{{ states.camera.front_garden_snapshot.attributes.entity_picture }}
  stream_source: rtsp://03cabcc9-ring-mqtt:8554/184516a77655_live