---
#-
#
#   ___ __ _ _ __ ___   ___ _ __ __ _
#  / __/ _` | '_ ` _ \ / _ \ '__/ _` |
# | (_| (_| | | | | | |  __/ | | (_| |
#  \___\__,_|_| |_| |_|\___|_|  \__,_|
#
#
#- from github.com/tmttn/home-assistant-config

- platform: xiaomi_cloud_map_extractor
  host: !secret ip_vacuum
  token: !secret xiaomi_cloud_token
  username: !secret xiaomi_cloud_username
  password: !secret xiaomi_cloud_password
  draw: ["all"]
  map_transformation:
    trim:
      left: 20
      top: 15
      right: 25
      bottom: 25
  attributes:
    - calibration_points
    - rooms
