---
#-
#
#   ___ __ _ _ __ ___   ___ _ __ __ _
#  / __/ _` | '_ ` _ \ / _ \ '__/ _` |
# | (_| (_| | | | | | |  __/ | | (_| |
#  \___\__,_|_| |_| |_|\___|_|  \__,_|
#
#
#- from github.com/tmttn/home-assistant-config

- platform: xiaomi_cloud_map_extractor
  host: 192.168.87.42
  token: !secret xiaomi_cloud_token
  username: !secret xiaomi_cloud_username
  password: !secret xiaomi_cloud_password
  draw: ['all']
  attributes:
    - calibration_points 