---
#-
#       _ _                 _
#   ___| (_)_ __ ___   __ _| |_ ___
#  / __| | | '_ ` _ \ / _` | __/ _ \
# | (__| | | | | | | | (_| | ||  __/
#  \___|_|_|_| |_| |_|\__,_|\__\___|
#
#
#- from github.com/basnijholt/home-assistant-config
- platform: mqtt
  name: Thermostat
  current_temperature_topic: events/central_heating/otmonitor/roomtemperature
  temperature_command_topic: actions/otmonitor/setpoint
  temperature_state_topic: events/central_heating/otmonitor/setpoint
  min_temp: 5
  max_temp: 35
  initial: 17
  modes:
    - heat
  temp_step: 0.5
  precision: 0.5
