---
- platform: mqtt
  name: Thermostat
  current_temperature_topic: events/central_heating/otmonitor/roomtemperature
  temperature_command_topic: actions/otmonitor/setpoint
  temperature_state_topic: events/central_heating/otmonitor/setpoint
  min_temp: 5
  max_temp: 35
  initial: 17
  temp_step: 0.5
  precision: 0.5

# XXX: There's also the following topic to set the outside temp:
# actions/otmonitor/outside
