---
#-
#  _ _       _     _
# | (_) __ _| |__ | |_ ___
# | | |/ _` | '_ \| __/ __|
# | | | (_| | | | | |_\__ \
# |_|_|\__, |_| |_|\__|___/
#      |___/
#
#- from github.com/tmttn/home-assistant-config

- platform: group
  name: Bedroom ceiling lights
  unique_id: bedroom_ceiling_lights
  entities:
    - light.bedroom_1
    - light.bedroom_2

- platform: group
  name: Bedroom lights
  unique_id: bedroom_lights
  entities:
    - light.bedroom_ceiling_lights
    - light.bedroom_bedside_tom

- platform: group
  name: Bed reading
  unique_id: bed_reading
  entities:
    - light.bedroom_bedside_tom

- platform: group
  name: Guest bedroom lights
  unique_id: guest_bedroom_lights
  entities:
    - light.guest_bedroom_bedside

- platform: group
  name: Guest bedroom bed reading
  unique_id: guest_bedroom_bed_reading
  entities:
    - light.guest_bedroom_bedside

- platform: group
  name: Automatic lights
  unique_id: automatic_lights
  entities:
    - light.kitchen_lights
    - light.toilet
    - light.outside_lights
    - light.christmas_lights_inside

- platform: group
  name: Kitchen lights
  unique_id: kitchen_lights
  entities:
    - light.kitchen_1
    - light.kitchen_2
    - light.kitchen_3

- platform: group
  name: Living room dining table lights
  unique_id: living_room_dining_table_lights
  entities:
    - light.dining_table_1
    - light.dining_table_2
    - light.dining_table_3
    - light.dining_table_4

- platform: group
  name: Living room middle lights
  unique_id: living_room_middle_lights
  entities:
    - light.living_room_middle_1
    - light.living_room_middle_2
    - light.living_room_middle_3
    - light.living_room_middle_4

- platform: group
  name: Living room lights
  unique_id: living_room_lights
  entities:
    - light.living_room_dining_table_lights
    - light.living_room_middle_lights
    - light.tv_led
    - light.hue_plug
    - light.shelly_plug_s_1

- platform: group
  name: Bathroom lights
  unique_id: bathroom_lights
  entities:
    - light.bathroom_1
    - light.bathroom_2
    - light.bathroom_3
    - light.bathroom_4

- platform: group
  name: Outside lights
  unique_id: outside_lights
  entities:
    - light.terrace_lights
    - light.shelly_plug_s_3

- platform: group
  name: Terrace lights
  unique_id: terrace_lights
  entities:
    - light.terrace_corner
    - light.terrace_wall
    - light.terrace_backdoor
    - light.shelly_plug_s_4

- platform: group
  name: Christmas lights inside
  unique_id: christmas_lights_inside
  entities:
    - light.shelly_plug_s_1
    - light.shelly_plug_s_2

- platform: group
  name: Christmas lights outside
  unique_id: christmas_lights_outside
  entities:
    - light.shelly_plug_s_3
    - light.shelly_plug_s_4

- platform: switch
  name: Hue plug
  entity_id: switch.hue_plug

- platform: switch
  name: Shelly Plug S 1
  entity_id: switch.shelly_plug_s_1

- platform: switch
  name: Shelly Plug S 2
  entity_id: switch.shelly_plug_s_2
  
- platform: switch
  name: Shelly Plug S 3
  entity_id: switch.shelly_plug_s_3

- platform: switch
  name: Shelly Plug S 4
  entity_id: switch.shelly_plug_s_4
