---
#-
#  _ _       _     _
# | (_) __ _| |__ | |_ ___
# | | |/ _` | '_ \| __/ __|
# | | | (_| | | | | |_\__ \
# |_|_|\__, |_| |_|\__|___/
#      |___/
#
#- from github.com/tmttn/home-assistant-config

- platform: group
  name: Bedroom ceiling lights
  entities:
    - light.bedroom_1
    - light.bedroom_2

- platform: group
  name: Bedroom lights
  entities:
    - light.bedroom_ceiling_lights
    - light.bedroom_bedside_tom

- platform: group
  name: Bed reading
  entities:
    - light.bedroom_bedside_tom

- platform: group
  name: Guest room lights
  entities:
    - light.guest_room_bedside

- platform: group
  name: Guest room bed reading
  entities:
    - light.guest_room_bedside

- platform: group
  name: Automatic lights
  entities:
    - light.kitchen_lights
    - light.toilet
    - light.outside_lights

- platform: group
  name: Kitchen lights
  entities:
    - light.kitchen_1
    - light.kitchen_2
    - light.kitchen_3

- platform: group
  name: Living room dining table lights
  entities:
    - light.dining_table_1
    - light.dining_table_2
    - light.dining_table_3
    - light.dining_table_4

- platform: group
  name: Living room middle lights
  entities:
    - light.living_room_middle_1
    - light.living_room_middle_2
    - light.living_room_middle_3
    - light.living_room_middle_4

- platform: group
  name: Living room lights
  entities:
    - light.living_room_dining_table_lights
    - light.living_room_middle_lights
    - light.tv_led
    - light.hue_plug

- platform: group
  name: Bathroom lights
  entities:
    - light.bathroom_1
    - light.bathroom_2
    - light.bathroom_3
    - light.bathroom_4

- platform: group
  name: Bed reading
  entities:
    - light.bedroom_bedside_tom

- platform: group
  name: Outside lights
  entities:
    - light.terrace_lights
    - light.outside_switch_1
    - light.outside_switch_2
    - light.outside_switch_3

- platform: group
  name: Terrace lights
  entities:
    - light.terrace_corner
    - light.terrace_wall
    - light.terrace_backdoor

- platform: switch
  name: Outside switch 1
  entity_id: switch.hombli_smart_outdoor_socket_1_socket_1

- platform: switch
  name: Outside switch 2
  entity_id: switch.hombli_smart_outdoor_socket_2_socket_1

- platform: switch
  name: Outside switch 3
  entity_id: switch.hombli_smart_outdoor_socket_3_socket_1

- platform: switch
  name: Hue plug
  entity_id: switch.hue_plug
