---
#-
#  _ _       _     _
# | (_) __ _| |__ | |_ ___
# | | |/ _` | '_ \| __/ __|
# | | | (_| | | | | |_\__ \
# |_|_|\__, |_| |_|\__|___/
#      |___/
#
#- from github.com/tmttn/home-assistant-config

- platform: group
  name: Bedroom lights
  entities:
    - light.grote_slaapkamer_1
    - light.grote_slaapkamer_2
    - light.grote_slaapkamer_nachtkastje_tom

- platform: group
  name: Automatic lights
  entities:
    - light.kitchen_lights
    - light.toilet

- platform: group
  name: Kitchen lights
  entities:
    - light.keuken_1
    - light.keuken_2
    - light.keuken_3

- platform: group
  name: Living room dining table lights
  entities:
    - light.living_eettafel_1
    - light.living_eettafel_2
    - light.living_eettafel_3
    - light.living_eettafel_4

- platform: group
  name: Living room middle lights
  entities:
    - light.living_midden_1
    - light.living_midden_2
    - light.living_midden_3
    - light.living_midden_4


- platform: group
  name: Living room lights
  entities:
    - light.living_room_dining_table_lights
    - light.living_room_middle_lights
    - light.living_tv_backdrop
    - light.de_kerstboom

- platform: group
  name: Bathroom lights
  entities:
    - light.badkamer_1
    - light.badkamer_2
    - light.badkamer_3
    - light.badkamer_4

- platform: group
  name: Bed reading
  entities:
    - light.grote_slaapkamer_nachtkastje_tom

- platform: group
  name: Terrace lights
  entities:
    - light.terras_hoek
    - light.terras_muurtje
    - light.terras_achterdeur