- platform: group
  name: Living room lights
  entities:
    - light.sphere_1
    - light.sphere_2
    - light.corner_living_room
    - light.ceiling_living_room
    - light.tv_led

- platform: group
  name: Bedroom lights
  entities:
    - light.philips_go
    - light.bamboo
    - light.ceiling_bedroom
    - light.lampan
    - light.bed_led

- platform: group
  name: Automatic lights
  entities:
    - light.ceiling_kitchen
    - light.kitchen_counter
    - light.toilet
    - light.ceiling_bathroom

- platform: group
  name: Kitchen lights
  entities:
    - light.ceiling_kitchen
    - light.kitchen_counter

- platform: switch
  name: Kitchen counter
  entity_id: switch.kitchen_counter

# - platform: group
#   name: Stairs lights
#   entities:
#     - light.stairs_up
#     - light.stairs_down

# - platform: group
#   name: Hall lights
#   entities:
#     - light.hall_1
#     - light.hall_2
#     - light.hall_3
