---
- platform: spotify
  client_id: !secret spotify_client_id
  client_secret: !secret spotify_client_secret

- platform: kef
  type: LS50
  name: KEF Speakers
  host: 192.168.178.206
  maximum_volume: 0.6
  volume_step: 0.05

- platform: webostv
  host: 192.168.178.157
  name: tv
