---
#-
#                     _ _                  _
#  _ __ ___   ___  __| (_) __ _      _ __ | | __ _ _   _  ___ _ __ ___
# | '_ ` _ \ / _ \/ _` | |/ _` |    | '_ \| |/ _` | | | |/ _ \ '__/ __|
# | | | | | |  __/ (_| | | (_| |    | |_) | | (_| | |_| |  __/ |  \__ \
# |_| |_| |_|\___|\__,_|_|\__,_|____| .__/|_|\__,_|\__, |\___|_|  |___/
#                             |_____|_|            |___/
#
#- from github.com/basnijholt/home-assistant-config
- platform: spotify
  client_id: !secret spotify_client_id
  client_secret: !secret spotify_client_secret

- platform: kef_custom
  type: LS50
  name: KEF LS50
  host: !secret ip_kef_ls50
  maximum_volume: 0.6
  volume_step: 0.05
  standby_time: 60

- platform: kef_custom
  type: LSX
  name: KEF LSX
  host: !secret ip_kef_lsx
  maximum_volume: 0.9
  volume_step: 0.05
  inverse_speaker_mode: true
  standby_time: 60
