---
- platform: spotify
  client_id: !secret spotify_client_id
  client_secret: !secret spotify_client_secret

- platform: kef
  type: LS50
  name: Living room speakers
  host: 192.168.178.206
  maximum_volume: 0.6
  volume_step: 0.05

- platform: kef
  type: LSX
  name: Bedroom speakers
  host: 192.168.178.73
  maximum_volume: 0.6
  volume_step: 0.05

- platform: webostv
  host: 192.168.178.157
  name: tv
  turn_on_action:
    service: wake_on_lan.send_magic_packet
    data:
      mac: !secret kef_mac_address
