---
- platform: spotify
  client_id: !secret spotify_client_id
  client_secret: !secret spotify_client_secret

- platform: kef_custom
  type: LS50
  name: KEF
  host: !secret ip_kef_ls50
  maximum_volume: 0.6
  volume_step: 0.05
  standby_time: 60

- platform: kef_custom
  type: LSX
  name: Bedroom speakers
  host: !secret ip_kef_lsx
  maximum_volume: 0.7
  volume_step: 0.05
  inverse_speaker_mode: true
  standby_time: 60
