---
- platform: spotify
  client_id: !secret spotify_client_id
  client_secret: !secret spotify_client_secret

- platform: kef
  type: LS50
  name: Living room speakers
  host: 192.168.1.5
  maximum_volume: 0.6
  volume_step: 0.05

- platform: kef
  type: LSX
  name: Bedroom speakers
  host: 192.168.1.6
  maximum_volume: 0.7
  volume_step: 0.05
  inverse_speaker_mode: true
