---
#-
#              _   _  __
#  _ __   ___ | |_(_)/ _|_   _
# | '_ \ / _ \| __| | |_| | | |
# | | | | (_) | |_| |  _| |_| |
# |_| |_|\___/ \__|_|_|  \__, |
#                        |___/
#
#- from github.com/basnijholt/home-assistant-config
- platform: webostv
  host: !secret ip_tv
  name: tv
  filename: webostv.conf

- platform: group
  name: all_iphones
  services:
    - service: mobile_app_basnijholt_iphone
    - service: mobile_app_marcella_iphone
