---
#-
#              _   _  __
#  _ __   ___ | |_(_)/ _|_   _
# | '_ \ / _ \| __| | |_| | | |
# | | | | (_) | |_| |  _| |_| |
# |_| |_|\___/ \__|_|_|  \__, |
#                        |___/
#
#- from github.com/tmttn/home-assistant-config
- platform: group
  name: all_iphones
  services:
    - service: mobile_app_bizzyphone
    - service: mobile_app_t_phone

- platform: group
  name: tom
  services:
    - service: mobile_app_bizzyphone

- platform: group
  name: all
  services:
    - service: mobile_app_bizzyphone
    - service: mobile_app_t_phone
