---
#-
#
#  ___  ___ _ __  ___  ___  _ __ ___
# / __|/ _ \ '_ \/ __|/ _ \| '__/ __|
# \__ \  __/ | | \__ \ (_) | |  \__ \
# |___/\___|_| |_|___/\___/|_|  |___/
#
#
#- from github.com/tmttn/home-assistant-config

#   ___  _   _
#  / _ \| |_| |__   ___ _ __ ___
# | | | | __| '_ \ / _ \ '__/ __|
# | |_| | |_| | | |  __/ |  \__ \
#  \___/ \__|_| |_|\___|_|  |___/
#
- platform: statistics
  name: Washing machine Today's Consumption
  unique_id: washing_machine_today_consumption
  entity_id: sensor.washing_machine_energy
  state_characteristic: total
  sampling_size: 86400 # make sure all data points of the last 24hrs are included
  max_age:
    hours: 24

- platform: statistics
  name: Humidity bathroom stats
  unique_id: humidity_bathroom_stats
  entity_id: sensor.multi_sensor_bathroom_humidity
  state_characteristic: mean
  sampling_size: 86400 # make sure all data points of the last 24hrs are included
  max_age:
    hours: 24

- platform: derivative
  source: sensor.multi_sensor_bathroom_humidity
  name: Humidity bathroom derivative
  unit_time: min
  time_window: "00:10:00"

- platform: statistics
  name: Humidity storage stats
  unique_id: humidity_storage_stats
  entity_id: sensor.multi_sensor_storage_humidity
  state_characteristic: mean
  sampling_size: 86400 # make sure all data points of the last 24hrs are included
  max_age:
    hours: 24

- platform: derivative
  source: sensor.multi_sensor_storage_humidity
  name: Humidity storage derivative
  unit_time: min
  time_window: "00:10:00"

- platform: min_max
  name: Temperature mean
  type: mean
  entity_ids:
    - sensor.temperature_living_room
    - sensor.temperature_bedroom
    - sensor.temperature_bathroom
    - sensor.temperature_kitchen
    - sensor.temperature_storage
    - sensor.temperature_bedroom_marthe

- platform: time_date
  display_options:
    - date
    - time

- platform: integration
  source: sensor.hombli_smart_outdoor_socket_1_power
  name: gas_burner_consumption
  unique_id: "gas_burner_consumption"
  unit_prefix: k
  round: 2

- platform: integration
  source: sensor.hombli_smart_outdoor_socket_2_power
  name: heat_pump_boiler_consumption
  unique_id: "heat_pump_boiler_consumption"
  unit_prefix: k
  round: 2

#  _____ _                  _                  _
# |_   _(_)_ __ ___   ___  | |_ _ __ __ _  ___| | _____ _ __ ___
#   | | | | '_ ` _ \ / _ \ | __| '__/ _` |/ __| |/ / _ \ '__/ __|
#   | | | | | | | | |  __/ | |_| | | (_| | (__|   <  __/ |  \__ \
#   |_| |_|_| |_| |_|\___|  \__|_|  \__,_|\___|_|\_\___|_|  |___/
#

- platform: history_stats
  name: Hours TV has been on last 7 days
  entity_id: media_player.tv
  state: "on"
  type: time
  duration:
    days: 7
  end: "{{ now() }}"

- platform: history_stats
  name: Times TV has been on last 7 days
  entity_id: media_player.tv
  state: "on"
  type: count
  duration:
    days: 7
  end: "{{ now() }}"

- platform: history_stats
  name: Hours dishwasher has been on last 7 days
  entity_id: binary_sensor.dishwasher
  state: "on"
  type: time
  duration:
    days: 7
  end: "{{ now() }}"

- platform: history_stats
  name: Times dishwasher has been on last 7 days
  entity_id: binary_sensor.dishwasher
  state: "on"
  type: count
  duration:
    days: 7
  end: "{{ now() }}"

- platform: history_stats
  name: Hours tumble dryer has been on last 7 days
  entity_id: binary_sensor.tumble_dryer
  state: "on"
  type: time
  duration:
    days: 7
  end: "{{ now() }}"

- platform: history_stats
  name: Times tumble dryer has been on last 7 days
  entity_id: binary_sensor.tumble_dryer
  state: "on"
  type: count
  duration:
    days: 7
  end: "{{ now() }}"

- platform: history_stats
  name: Hours espresso machine has been on last 7 days
  entity_id: binary_sensor.espresso_machine
  state: "on"
  type: time
  duration:
    days: 7
  end: "{{ now() }}"

- platform: history_stats
  name: Times espresso machine has been on last 7 days
  entity_id: binary_sensor.espresso_machine
  state: "on"
  type: count
  duration:
    days: 7
  end: "{{ now() }}"

- platform: history_stats
  name: Hours washing machine has been on last 7 days
  entity_id: binary_sensor.washing_machine
  state: "on"
  type: time
  duration:
    days: 7
  end: "{{ now() }}"

- platform: history_stats
  name: Times washing machine has been on last 7 days
  entity_id: binary_sensor.washing_machine
  state: "on"
  type: count
  duration:
    days: 7
  end: "{{ now() }}"

- platform: history_stats
  name: Hours bedroom lights have been on last 7 days
  entity_id: light.bedroom_lights
  state: "on"
  type: time
  duration:
    days: 7
  end: "{{ now() }}"

- platform: history_stats
  name: Hours guest bedroom lights have been on last 7 days
  entity_id: light.guest_bedroom_lights
  state: "on"
  type: time
  duration:
    days: 7
  end: "{{ now() }}"

- platform: history_stats
  name: Hours living room lights have been on last 7 days
  entity_id: light.living_room_lights
  state: "on"
  type: time
  duration:
    days: 7
  end: "{{ now() }}"

- platform: history_stats
  name: Hours toilet light has been on last 7 days
  entity_id: light.toilet
  state: "on"
  type: time
  duration:
    days: 7
  end: "{{ now() }}"

- platform: history_stats
  name: Hours kitchen lights have been on last 7 days
  entity_id: light.kitchen_lights
  state: "on"
  type: time
  duration:
    days: 7
  end: "{{ now() }}"

- platform: history_stats
  name: Hours bathroom lights have been on last 7 days
  entity_id: light.bathroom_lights
  state: "on"
  type: time
  duration:
    days: 7
  end: "{{ now() }}"

- platform: history_stats
  name: Hours terrace lights have been on last 7 days
  entity_id: light.terrace_lights
  state: "on"
  type: time
  duration:
    days: 7
  end: "{{ now() }}"

- platform: history_stats
  name: Hours outside lights have been on last 7 days
  entity_id: light.outside_lights
  state: "on"
  type: time
  duration:
    days: 7
  end: "{{ now() }}"

# __        __         _      _   _                  _                  _
# \ \      / /__  _ __| | __ | |_(_)_ __ ___   ___  | |_ _ __ __ _  ___| | _____ _ __
#  \ \ /\ / / _ \| '__| |/ / | __| | '_ ` _ \ / _ \ | __| '__/ _` |/ __| |/ / _ \ '__|
#   \ V  V / (_) | |  |   <  | |_| | | | | | |  __/ | |_| | | (_| | (__|   <  __/ |
#    \_/\_/ \___/|_|  |_|\_\  \__|_|_| |_| |_|\___|  \__|_|  \__,_|\___|_|\_\___|_|
#

- platform: history_stats
  name: Time at work this week
  entity_id: person.tom
  state: Work
  type: time
  start: >
    {{ states("sensor.timestamp_start_of_today")|float(default=0) - now().weekday() * 86400 }}
  end: "{{ now() }}"

- platform: history_stats
  name: Time at work today
  entity_id: person.tom
  state: Work
  type: time
  start: >
    {{ states("sensor.timestamp_start_of_today")|float(default=0) - 0 * 86400 }}
  duration:
    hours: 24

- platform: history_stats
  name: Time at work on Monday
  entity_id: person.tom
  state: Work
  type: time
  duration:
    hours: 24
  start: >
    {% set day = now().weekday() - 0 %}
    {% if day < 0 %}{% set day = day + 7 %}{% endif %}
    {{ states("sensor.timestamp_start_of_today")|float(default=0) - day * 86400}}

- platform: history_stats
  name: Time at work on Tuesday
  entity_id: person.tom
  state: Work
  type: time
  duration:
    hours: 24
  start: >
    {% set day = now().weekday() - 1 %}
    {% if day < 0 %}{% set day = day + 7 %}{% endif %}
    {{ states("sensor.timestamp_start_of_today")|float(default=0) - day * 86400}}

- platform: history_stats
  name: Time at work on Wednessday
  entity_id: person.tom
  state: Work
  type: time
  duration:
    hours: 24
  start: >
    {% set day = now().weekday() - 2 %}
    {% if day < 0 %}{% set day = day + 7 %}{% endif %}
    {{ states("sensor.timestamp_start_of_today")|float(default=0) - day * 86400}}

- platform: history_stats
  name: Time at work on Thursday
  entity_id: person.tom
  state: Work
  type: time
  duration:
    hours: 24
  start: >
    {% set day = now().weekday() - 3 %}
    {% if day < 0 %}{% set day = day + 7 %}{% endif %}
    {{ states("sensor.timestamp_start_of_today")|float(default=0) - day * 86400}}

- platform: history_stats
  name: Time at work on Friday
  entity_id: person.tom
  state: Work
  type: time
  duration:
    hours: 24
  start: >
    {% set day = now().weekday() - 4 %}
    {% if day < 0 %}{% set day = day + 7 %}{% endif %}
    {{ states("sensor.timestamp_start_of_today")|float(default=0) - day * 86400}}

# Waste management
- platform: afvalbeheer
  wastecollector: Limburg.NET
  resources:
    - restafval
    - gft
    - papier
    - pmd
  postcode: !secret postal_code
  streetname: !secret street_name
  cityname: !secret city_name
  streetnumber: !secret street_number
  upcomingsensor: 1
  builtinicons: 1
  builtiniconsnew: 1
  dutch: 1
  dayofweekonly: 1
