---
#-
#
#  ___  ___ _ __  ___  ___  _ __ ___
# / __|/ _ \ '_ \/ __|/ _ \| '__/ __|
# \__ \  __/ | | \__ \ (_) | |  \__ \
# |___/\___|_| |_|___/\___/|_|  |___/
#
#
#- from github.com/basnijholt/home-assistant-config

#  _____                    _       _
# |_   _|__ _ __ ___  _ __ | | __ _| |_ ___    ___  ___ _ __  ___  ___  _ __ ___
#   | |/ _ \ '_ ` _ \| '_ \| |/ _` | __/ _ \  / __|/ _ \ '_ \/ __|/ _ \| '__/ __|
#   | |  __/ | | | | | |_) | | (_| | ||  __/  \__ \  __/ | | \__ \ (_) | |  \__ \
#   |_|\___|_| |_| |_| .__/|_|\__,_|\__\___|  |___/\___|_| |_|___/\___/|_|  |___/
#                    |_|

- platform: template
  sensors:
    washing_machine_watts:
      value_template: >
        {{ state_attr("switch.washing_machine", "current_power_w") | replace(" W", "") | float("Unavailable") }}
      unit_of_measurement: Watt
      friendly_name: Washing machine usage

    dishwasher_watts:
      value_template: >
        {{ state_attr("switch.dishwasher", "current_power_w") | replace(" W", "") | float("Unavailable") }}
      unit_of_measurement: Watt
      friendly_name: Dishwasher usage

    count_automations:
      entity_id: sensor.date
      icon_template: mdi:autorenew
      value_template: "{{ states.automation | count }}"

    count_scripts:
      entity_id: sensor.date
      icon_template: mdi:script-text-outline
      value_template: "{{ states.script| count }}"

    count_device_trackers:
      entity_id: sensor.date
      icon_template: mdi:map-marker
      value_template: "{{ states.device_tracker | count }}"

    count_binary_sensors:
      entity_id: sensor.date
      icon_template: mdi:unfold-more-horizontal
      value_template: "{{ states.binary_sensor| count }}"

    count_sensors:
      entity_id: sensor.date
      icon_template: mdi:resistor
      value_template: "{{ states.sensor | count }}"

    count_switches:
      entity_id: sensor.date
      icon_template: mdi:light-switch
      value_template: "{{ states.switch | count }}"

    count_zones:
      entity_id: sensor.date
      icon_template: mdi:map-marker-radius
      value_template: "{{ states.zone | count }}"

    count_input_booleans:
      entity_id: sensor.date
      icon_template: mdi:toggle-switch
      value_template: "{{ states.input_boolean | count }}"

    count_input_numbers:
      entity_id: sensor.date
      icon_template: mdi:numeric
      value_template: "{{ states.input_number | count }}"

    count_input_texts:
      entity_id: sensor.date
      icon_template: mdi:alphabetical
      value_template: "{{ states.input_text | count }}"

    count_input_selects:
      entity_id: sensor.date
      icon_template: mdi:view-list
      value_template: "{{ states.input_select | count }}"

    count_input_datetimes:
      entity_id: sensor.date
      icon_template: mdi:calendar-clock
      value_template: "{{ states.input_datetime | count }}"

    favorite_playlist_of_nearest_person:
      value_template: >
        {% if state_attr('proximity.home', 'nearest') == "basnijholt-iphone"%}
        6rPTm9dYftKcFAfwyRqmDZ
        {% else %}
        2Alq4aFJY8jRA2MnBL5d9A
        {% endif %}

    tv_volume:
      value_template: >
        {{ state_attr("media_player.tv", "volume_level") }}
      unit_of_measurement: "%"

    kef_ls50_volume:
      value_template: >
        {{ state_attr("media_player.kef_ls50", "volume_level") }}
      unit_of_measurement: "%"

    kef_lsx_volume:
      value_template: >
        {{ state_attr("media_player.kef_lsx", "volume_level") }}
      unit_of_measurement: "%"

    timestamp_start_of_today:
      value_template: >
        {{ as_timestamp(now().replace(hour=0).replace(minute=0).replace(second=0)) }}
      unit_of_measurement: "s"
      entity_id: sensor.date

    time_at_work_prognosis:
      value_template: >
        {% set day = [now().weekday(), 4] | min %}
        {% set t_total = states("sensor.time_at_work_this_week")|float %}
        {% set t_today = states("sensor.time_at_work_today")|float %}
        {% set hours_per_day_including_today = t_total / (day + 1) %}
        {% set hours_per_day_excluding_today = (t_total - t_today ) / (day + 10**-16) %}
        {% set seven_oclock = as_timestamp(now().replace(hour=19).replace(minute=0).replace(second=0)) %}

        {% if t_today > hours_per_day_excluding_today
              or (not is_state("person.bas", "Work") and t_today > 0)
              or (as_timestamp(now()) > seven_oclock)
              or day == 0
              or now().weekday() > 4
              or 5 * hours_per_day_including_today > 40 %}
          {% set hours_per_day = hours_per_day_including_today %}
        {% else %}
          {% set hours_per_day = hours_per_day_excluding_today %}
        {% endif %}

        {{ (5 * hours_per_day)|round(2) }}
      unit_of_measurement: h

    daily_power:
      friendly_name: Daily Power
      unit_of_measurement: kWh
      value_template: >
        {{ states("sensor.daily_power_offpeak")|float + states("sensor.daily_power_peak")|float }}

    monthly_power:
      friendly_name: Monthly Power
      unit_of_measurement: kWh
      value_template: >
        {{ states("sensor.monthly_power_offpeak")|float + states("sensor.monthly_power_peak")|float }}

    daily_gas_cost:
      friendly_name: Daily Power
      unit_of_measurement: €
      value_template: >
        {{ states("sensor.daily_gas")|float * 0.7884 + (0.1480 + 0.3554) }}

    monthly_gas_cost:
      friendly_name: Monthly Power
      unit_of_measurement: €
      value_template: >
        {{ states("sensor.monthly_gas")|float * 0.7884 }}

    daily_power_cost:
      friendly_name: Daily Power
      unit_of_measurement: €
      value_template: >
        {{ states("sensor.daily_power_offpeak")|float * 0.2307
           + states("sensor.daily_power_peak")|float * 0.2479 }}

    monthly_power_cost:
      friendly_name: Monthly Power
      unit_of_measurement: €
      value_template: >
        {{ states("sensor.monthly_power_offpeak")|float * 0.2307
           + states("sensor.monthly_power_peak")|float * 0.2479 }}

    daily_energy_fixed_cost:
      friendly_name: Fixed daily energy cost (gas and power)
      unit_of_measurement: €
      entity_id: sensor.date  # To get rid of the warning
      value_template: >
        {{ (0.1480 + 0.3554) + (0.1480 + 0.6293) }}

    monthly_energy_fixed_cost:
      friendly_name: Fixed daily energy cost (gas and power)
      unit_of_measurement: €
      entity_id: sensor.date
      value_template: >
        {{ states("sensor.daily_energy_fixed_cost")|float * now().day }}

#   ___  _   _
#  / _ \| |_| |__   ___ _ __ ___
# | | | | __| '_ \ / _ \ '__/ __|
# | |_| | |_| | | |  __/ |  \__ \
#  \___/ \__|_| |_|\___|_|  |___/
#

# XXX: not used
- platform: min_max
  name: Temperature mean
  type: mean
  entity_ids:
    - sensor.temperature_living_room
    - sensor.temperature_bedroom
    - sensor.temperature_bathroom
    - sensor.temperature_hall

- platform: time_date
  display_options:
     - date

# XXX: wait until 0.105
# - platform: derivative
#   source: sensor.gas_consumption
#   name: Gas per hour
#   unit: m³/s

- platform: command_line
  name: RPi CPU Temperature
  command: "cat /sys/class/thermal/thermal_zone0/temp"
  unit_of_measurement: "°C"
  value_template: "{{ value | multiply(0.001) | round(2) }}"

- platform: command_line
  name: RPi GPU Temperature
  command: "/opt/vc/bin/vcgencmd measure_temp"
  unit_of_measurement: "°C"
  value_template: '{{ value | replace("temp=", "") | replace("''C", "") }}'

- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: "/"
    - type: memory_use_percent
    - type: network_in
      arg: eth0
    - type: network_out
      arg: eth0
    - type: processor_use
    - type: last_boot

- platform: dnsip

- platform: version
  name: Installed Version
  source: local

- platform: version
  name: Latest Available Version
  beta: false
  image: raspberrypi4
  source: hassio

- platform: uptime
  unit_of_measurement: hours

- platform: filesize
  file_paths:
    - /config/home-assistant_v2.db
    - /config/.storage/lovelace

- platform: github
  access_token: !secret hass_sensor_gh_token
  repositories:
    - path: "basnijholt/lovelace-ios-dark-mode-theme"
    - path: "basnijholt/lovelace-ios-light-mode-theme"
    - path: "python-adaptive/adaptive"
    - path: "basnijholt/home-assistant-config"

# __        __         _      _   _                  _                  _
# \ \      / /__  _ __| | __ | |_(_)_ __ ___   ___  | |_ _ __ __ _  ___| | _____ _ __
#  \ \ /\ / / _ \| '__| |/ / | __| | '_ ` _ \ / _ \ | __| '__/ _` |/ __| |/ / _ \ '__|
#   \ V  V / (_) | |  |   <  | |_| | | | | | |  __/ | |_| | | (_| | (__|   <  __/ |
#    \_/\_/ \___/|_|  |_|\_\  \__|_|_| |_| |_|\___|  \__|_|  \__,_|\___|_|\_\___|_|
#

- platform: history_stats
  name: Time at work this week
  entity_id: person.bas
  state: Work
  type: time
  start: >
    {{ states("sensor.timestamp_start_of_today")|float - now().weekday() * 86400 }}
  end: "{{ now() }}"

- platform: history_stats
  name: Time at work today
  entity_id: person.bas
  state: Work
  type: time
  start: >
    {{ states("sensor.timestamp_start_of_today")|float - 0 * 86400 }}
  duration:
    hours: 24

- platform: history_stats
  name: Time at work on Monday
  entity_id: person.bas
  state: Work
  type: time
  duration:
    hours: 24
  start: >
    {% set day = now().weekday() - 0 %}
    {% if day < 0 %}{% set day = day + 7 %}{% endif %}
    {{ states("sensor.timestamp_start_of_today")|float - day * 86400}}

- platform: history_stats
  name: Time at work on Tuesday
  entity_id: person.bas
  state: Work
  type: time
  duration:
    hours: 24
  start: >
    {% set day = now().weekday() - 1 %}
    {% if day < 0 %}{% set day = day + 7 %}{% endif %}
    {{ states("sensor.timestamp_start_of_today")|float - day * 86400}}

- platform: history_stats
  name: Time at work on Wednessday
  entity_id: person.bas
  state: Work
  type: time
  duration:
    hours: 24
  start: >
    {% set day = now().weekday() - 2 %}
    {% if day < 0 %}{% set day = day + 7 %}{% endif %}
    {{ states("sensor.timestamp_start_of_today")|float - day * 86400}}

- platform: history_stats
  name: Time at work on Thursday
  entity_id: person.bas
  state: Work
  type: time
  duration:
    hours: 24
  start: >
    {% set day = now().weekday() - 3 %}
    {% if day < 0 %}{% set day = day + 7 %}{% endif %}
    {{ states("sensor.timestamp_start_of_today")|float - day * 86400}}

- platform: history_stats
  name: Time at work on Friday
  entity_id: person.bas
  state: Work
  type: time
  duration:
    hours: 24
  start: >
    {% set day = now().weekday() - 4 %}
    {% if day < 0 %}{% set day = day + 7 %}{% endif %}
    {{ states("sensor.timestamp_start_of_today")|float - day * 86400}}

#  ____                                          _    ____
# |  _ \ _____      _____ _ __    __ _ _ __   __| |  / ___| __ _ ___
# | |_) / _ \ \ /\ / / _ \ '__|  / _` | '_ \ / _` | | |  _ / _` / __|
# |  __/ (_) \ V  V /  __/ |    | (_| | | | | (_| | | |_| | (_| \__ \
# |_|   \___/ \_/\_/ \___|_|     \__,_|_| |_|\__,_|  \____|\__,_|___/

# From the "Meterkast" Home Assistant

- platform: mqtt
  state_topic: homeassistant/sensor/gas_consumption/state
  unit_of_measurement: m3
  name: Gas Consumption
  icon: mdi:fire

- platform: mqtt
  state_topic: homeassistant/sensor/hourly_gas_consumption/state
  unit_of_measurement: m3/h
  name: Hourly Gas Consumption
  icon: mdi:fire

- platform: mqtt
  state_topic: homeassistant/sensor/long_power_failure_count/state
  name: Long Power Failure Count
  icon: mdi:flash-off

- platform: mqtt
  state_topic: homeassistant/sensor/power_consumption/state
  unit_of_measurement: kW
  name: Power Consumption
  icon: mdi:flash

- platform: mqtt
  state_topic: homeassistant/sensor/power_consumption_low/state
  unit_of_measurement: kWh
  name: Power Consumption (low)
  icon: mdi:flash

- platform: mqtt
  state_topic: homeassistant/sensor/power_consumption_normal/state
  unit_of_measurement: kWh
  name: Power Consumption (normal)
  icon: mdi:flash

- platform: mqtt
  state_topic: homeassistant/sensor/power_consumption_phase_l1/state
  unit_of_measurement: kW
  name: Power Consumption Phase L1
  icon: mdi:flash

- platform: mqtt
  state_topic: homeassistant/sensor/power_consumption_phase_l2/state
  name: Power Consumption Phase L2
  icon: mdi:flash

- platform: mqtt
  state_topic: homeassistant/sensor/power_consumption_phase_l3/state
  name: Power Consumption Phase L3
  icon: mdi:flash

- platform: mqtt
  state_topic: homeassistant/sensor/power_consumption_total/state
  name: Power Consumption (total)
  icon: mdi:flash

- platform: mqtt
  state_topic: homeassistant/sensor/power_production/state
  unit_of_measurement: kW
  name: Power Production
  icon: mdi:flash

- platform: mqtt
  state_topic: homeassistant/sensor/power_production_low/state
  unit_of_measurement: kWh
  name: Power Production (low)
  icon: mdi:flash

- platform: mqtt
  state_topic: homeassistant/sensor/power_production_normal/state
  unit_of_measurement: kWh
  name: Power Production (normal)
  icon: mdi:flash

- platform: mqtt
  state_topic: homeassistant/sensor/power_production_phase_l1/state
  unit_of_measurement: kW
  name: Power Production Phase L1
  icon: mdi:flash

- platform: mqtt
  state_topic: homeassistant/sensor/power_production_phase_l2/state
  name: Power Production Phase L2
  icon: mdi:flash

- platform: mqtt
  state_topic: homeassistant/sensor/power_production_phase_l3/state
  name: Power Production Phase L3
  icon: mdi:flash

- platform: mqtt
  state_topic: homeassistant/sensor/power_tariff/state
  name: Power Tariff
  icon: mdi:flash

- platform: mqtt
  state_topic: homeassistant/sensor/voltage_phase_l1/state
  name: Voltage Phase L1

- platform: mqtt
  state_topic: homeassistant/sensor/voltage_phase_l2/state
  name: Voltage Phase L2

- platform: mqtt
  state_topic: homeassistant/sensor/voltage_phase_l3/state
  name: Voltage Phase L3

- platform: mqtt
  state_topic: homeassistant/sensor/voltage_sags_phase_l1/state
  name: Voltage Sags Phase L1
  icon: mdi:pulse

- platform: mqtt
  state_topic: homeassistant/sensor/voltage_sags_phase_l2/state
  name: Voltage Sags Phase L2
  icon: mdi:pulse

- platform: mqtt
  state_topic: homeassistant/sensor/voltage_sags_phase_l3/state
  name: Voltage Sags Phase L3
  icon: mdi:pulse

- platform: mqtt
  state_topic: homeassistant/sensor/voltage_swells_phase_l1/state
  name: Voltage Swells Phase L1
  icon: mdi:pulse

- platform: mqtt
  state_topic: homeassistant/sensor/voltage_swells_phase_l2/state
  name: Voltage Swells Phase L2
  icon: mdi:pulse

- platform: mqtt
  state_topic: homeassistant/sensor/voltage_swells_phase_l3/state
  name: Voltage Swells Phase L3
  icon: mdi:pulse

#  ____  _             _
# |  _ \| | __ _ _ __ | |_ ___
# | |_) | |/ _` | '_ \| __/ __|
# |  __/| | (_| | | | | |_\__ \
# |_|   |_|\__,_|_| |_|\__|___/
#

- platform: miflora
  mac: '80:EA:CA:89:1A:4E'  # Balsamico nr. 3

# https://www.growabonsaitree.com/species/ficus-bonsai/
- platform: mqtt
  state_topic: homeassistant/sensor/mi_flora_ficus_microcarpa_ginseng_battery/state
  unit_of_measurement: "%"
  name: "Mi Flora: Ficus microcarpa Ginseng Battery"
  icon: mdi:battery-charging

- platform: mqtt
  state_topic: homeassistant/sensor/mi_flora_ficus_microcarpa_ginseng_conductivity/state
  unit_of_measurement: µS/cm
  name: "Mi Flora: Ficus microcarpa Ginseng Conductivity"
  icon: mdi:flash-circle

- platform: mqtt
  state_topic: homeassistant/sensor/mi_flora_ficus_microcarpa_ginseng_light_intensity/state
  unit_of_measurement: lx
  name: "Mi Flora: Ficus microcarpa Ginseng Light intensity"
  icon: mdi:white-balance-sunny

- platform: mqtt
  state_topic: homeassistant/sensor/mi_flora_ficus_microcarpa_ginseng_moisture/state
  unit_of_measurement: "%"
  name: "Mi Flora: Ficus microcarpa Ginseng Moisture"
  icon: mdi:water-percent

- platform: mqtt
  state_topic: homeassistant/sensor/mi_flora_ficus_microcarpa_ginseng_temperature/state
  unit_of_measurement: °C
  name: "Mi Flora: Ficus microcarpa Ginseng Temperature"
  icon: mdi:thermometer

- platform: mqtt
  state_topic: homeassistant/sensor/mi_flora_kentia_palm_battery/state
  unit_of_measurement: "%"
  name: "Mi Flora: Flora Kentia Battery"
  icon: mdi:battery-charging

- platform: mqtt
  state_topic: homeassistant/sensor/mi_flora_kentia_palm_conductivity/state
  unit_of_measurement: µS/cm
  name: "Mi Flora: Flora Kentia Conductivity"
  icon: mdi:flash-circle

- platform: mqtt
  state_topic: homeassistant/sensor/mi_flora_kentia_palm_light_intensity/state
  unit_of_measurement: lx
  name: "Mi Flora: Flora Kentia Light intensity"
  icon: mdi:white-balance-sunny

- platform: mqtt
  state_topic: homeassistant/sensor/mi_flora_kentia_palm_moisture/state
  unit_of_measurement: "%"
  name: "Mi Flora: Flora Kentia Moisture"
  icon: mdi:water-percent

- platform: mqtt
  state_topic: homeassistant/sensor/mi_flora_kentia_palm_temperature/state
  unit_of_measurement: °C
  name: "Mi Flora: Flora Kentia Temperature"
  icon: mdi:thermometer
