---
- platform: template
  switches:
    vacuum_mode:
      value_template: "{{ is_state('vacuum.xiaomi_vacuum_cleaner', 'cleaning')}}"
      turn_on:
        service: vacuum.start
        entity_id: vacuum.xiaomi_vacuum_cleaner
      turn_off:
        service: vacuum.return_to_base
        entity_id: vacuum.xiaomi_vacuum_cleaner

- platform: circadian_lighting
  lights_rgb:
    - light.toilet
    - light.ceiling_kitchen
    - light.ceiling_bathroom
    - light.stairs_up
    - light.stairs_down
    - light.hall_1
    - light.hall_2
    - light.hall_3
  sleep_entity: input_boolean.sleep_mode
  sleep_state: "on"
  sleep_colortemp: 1000
  sleep_brightness: 1
  min_brightness: 70