---
#-
#               _ _       _
#  _____      _(_) |_ ___| |__   ___  ___
# / __\ \ /\ / / | __/ __| '_ \ / _ \/ __|
# \__ \\ V  V /| | || (__| | | |  __/\__ \
# |___/ \_/\_/ |_|\__\___|_| |_|\___||___/
#
#
#- from github.com/basnijholt/home-assistant-config
- platform: template
  switches:
    vacuum_mode:
      value_template: >
        {{ is_state("vacuum.xiaomi_vacuum_cleaner", "cleaning")}}
      turn_on:
        service: vacuum.start
        entity_id: vacuum.xiaomi_vacuum_cleaner
      turn_off:
        service: vacuum.return_to_base
        entity_id: vacuum.xiaomi_vacuum_cleaner

    kef_lsx:
      friendly_name: Bedroom speakers
      value_template: >
        {{ is_state("media_player.kef_lsx", "on") }}
      availability_template: >
        {{ not is_state("media_player.kef_lsx", "unavailable") }}
      turn_on:
        service: media_player.turn_on
        entity_id: media_player.kef_lsx
      turn_off:
        service: media_player.turn_off
        entity_id: media_player.kef_lsx

- platform: circadian_lighting
  lights_rgb:
    - light.toilet
    - light.ceiling_kitchen
    - light.ceiling_bathroom
  lights_ct:  # XXX: these lights can handle `color_temp = [153, 500]` but maybe it is alright?
    - light.stairs_up
    - light.stairs_down
    - light.hall_1
    - light.hall_2
    - light.hall_3
  sleep_entity: input_boolean.sleep_mode
  sleep_state: "on"
  sleep_colortemp: 1000
  sleep_brightness: 1
  min_brightness: 70
