---
#-
#
# __   ____ _  ___ _   _ _   _ _ __ ___
# \ \ / / _` |/ __| | | | | | | '_ ` _ \
#  \ V / (_| | (__| |_| | |_| | | | | | |
#   \_/ \__,_|\___|\__,_|\__,_|_| |_| |_|
#
#
#- from github.com/basnijholt/home-assistant-config
- platform: xiaomi_miio
  host: !secret ip_vacuum
  token: !secret vacuum_token
